/**
 * pims-web org.pimslims.utils.testmodel MolComponentTest.java
 * 
 * @author Marc Savitsky
 * @date 10 Oct 2007
 * 
 *       Protein Information Management System
 * @version: 1.3
 * 
 *           Copyright (c) 2007 Marc Savitsky
 * 
 */
package org.pimslims.utils.testmodel;

import java.util.HashMap;
import java.util.Map;

import junit.framework.Assert;
import junit.framework.TestCase;

import org.pimslims.dao.AbstractModel;
import org.pimslims.dao.ModelImpl;
import org.pimslims.dao.WritableVersion;
import org.pimslims.exception.AccessException;
import org.pimslims.exception.ConstraintException;
import org.pimslims.model.molecule.Molecule;
import org.pimslims.model.molecule.Substance;

/**
 * MolComponentTest
 * 
 */
@Deprecated
// obsolete, not a useful test
public class MolComponentTest extends TestCase {

    /**
     * 
     */
    private static final String SEQ3 =
        "GTAGGACAGTGACGACTAAGACTCCAGTGCATTTCTATCGTAACCGGGCGCGGGGGAGCGCAGATCGGCGCCCAGCAATCACAGAAGCCGACAAGGCGTT";

    /**
     * 
     */
    private static final String SEQ2 =
        "CAGCTACAGTGACGACTAAGACTCCAGTGCATTTCTATCGTAACCGGGCGCGGGGGAGCGCAGATCGGCGCCCAGCAATCACAGAAGCCGACAAGGCGTT";

    /**
     * 
     */
    private static final String SEQ1 =
        "CTCGGCCCAACAAAATGGCGGCGGCAGCGGTGTCGCTTTGTTTCCGCGGCTCCTGCGGCGGTGGCAGTGGTAGCGGCCTTTGAGCTGTGGGGAGGTTCCA";

    public static final String SEQ_STRING = "CTCGGCCCAACAAAATGGCGGCGGCAGCGGTGTCGCTTTGTTTCCGCGGCTCCTGCGGCGG"
        + "AGACTCCAGTGCATTTCTATCGTAACCGGGCGCGGGGGAGCGCAGATCGGCGCCCAGCAAT"
        + "CACAGAAGCCGACAAGGCGTTCAAGCGAAAACATGACCGCTGAGCCCATGAGTGAAAGCAA"
        + "GTTGAATACATTGGTGCAGAAGCTTCATGACTTCCTTGCACACTCATCAGAAGAATCTGAA"
        + "GAAGTAACTCTGATATGATGGAAAACAGCAAGGAAGAGGGAACTAGCTCTTCAGAAAAATC"
        + "CAAGTCTTCAGGATCGTCACGATCAAAGAGGAAACCTTCAATTGTAACAAAGTATGTAGAA"
        + "TCAGATGATGAAAAACCTTTGGATGATGAAACTGTAAATGAAGATGCGTCTAATGAAAATT"
        + "CAGAAAATGATATTACTATGCAGAGCTTGCCAAAAGGTACAGTGATTGTACAGCCAGAGCC"
        + "AGTGCTGAATGAAGACAAAGATGATTTTAAAGGGCCTGAATTTAGAAGCAGAAGTAAAATG"
        + "AAAACTGAAAATCTCAAAAAACGCGGAGAAGATGGGCTTCATGGGATTGTGAGCTGCACTG"
        + "CTTGTGGACAACAGGTCAATCATTTTCAAAAAGATTCCATTTATAGACACCCTTCATTGCA"
        + "AGTTCTTATTTGTAAGAATTGCTTTAAGTATTACATGAGTGATGATATTAGCCGTGACTCA"
        + "GATGGAATGGATGAACAATGTAGGTGGTGTGCGGAAGGTGGAAACTTGATTTGTTGTGACT"
        + "TTTGCCATAATGCTTTCTGCAAGAAATGCATTCTACGCAACCTTGGTCGAAAGGAGTTGTC"
        + "CACAATAATGGATGAAAACAACCAATGGTATTGCTACATTTGTCACCCAGAGCCTTTGTTG"
        + "GACTTGGTCACTGCATGTAACAGCGTATTTGAGAATTTAGAACAGTTGTTGCAGCAAAATA"
        + "AGAAGAAGATAAAAGTTGACAGTGAAAAGAGTAATAAAGTATATGAACATACATCCAGATT"
        + "TTCTCCAAAGAAGACTAGTTCAAATTGTAATGGAGAAGAAAAGAAATTAGATGATTCCTGT"
        + "TCTGGCTCTGTAACCTACTCTTATTCCGCACTAATTGTGCCCAAAGAGATGATTAAGAAGG"
        + "CAAAAAAACTGATTGAGACCACAGCCAACATGAACTCCAGTTATGTTAAATTTTTAAAGCA"
        + "GGCAACAGATAATTCAGAAATCAGTTCTGCTACAAAATTACGTCAGCTTAAGGCTTTTAAG"
        + "TCTGTGTTGGCTGATATTAAGAAGGCTCATCTTGCATTGGAAGAAGACTTAAATTCCGAGT"
        + "TTCGAGCGATGGATGCTGTAAACAAAGAGAAAAATACCAAAGAGCATAAAGTCATAGATGC"
        + "TAAGTTTGAAACAAAAGCACGAAAAGGAGAAAAACCTTGTGCTTTGGAAAAGAAGGATATT"
        + "TCAAAGTCAGAAGCTAAACTTTCAAGAAAACAGGTAGATAGTGAGCACATGCATCAGAATG"
        + "TTCCAACAGAGGAACAAAGAACAAATAAAAGTACCGGTGGTGAACATAAGAAATCTGATAG"
        + "AAAAGAAGAACCTCAATATGAACCTGCCAACACTTCTGAAGATTTAGACATGGATATTGTG"
        + "TCTGTTCCTTCCTCAGTTCCAGAAGACATTTTTGAGAATCTTGAGACTGCTATGGAAGTTC"
        + "AGAGTTCAGTTGATCATCAAGGGGATGGCAGCAGTGGAACTGAACAAGAAGTGGAGAGTTC"
        + "ATCTGTAAAATTAAATATTTCTTCAAAAGACAACAGAGGAGGTATTAAATCAAAAACTACA"
        + "GCTAAAGTAACAAAAGAATTATATGTTAAACTCACTCCTGTTTCCCTTTCTAATTCCCCAA"
        + "TTAAAGGTGCTGATTGTCAGGAAGTTCCACAAGATAAAGATGGCTATAAAAGTTGTGGTCT"
        + "GAACCCCAAGTTAGAGAAATGTGGACTTGGACAGGAAAACAGTGATAATGAGCATTTGGTT"
        + "GAAAATGAAGTTTCATTACTTTTAGAGGAATCTGATCTTCGAAGATCCCCACGTGTAAAGA"
        + "CTACACCCTTGAGGCGACCGACAGAAACTAACCCTGTAACATCTAATTCAGATGAAGAATG"
        + "TAATGAAACAGTTAAGGAGAAACAAAAACTATCAGTTCCAGTGAGAAAAAAGGATAAGCGT"
        + "AATTCTTCTGACAGTGCTATAGATAATCCTAAGCCTAATAAATTGCCAAAATCTAAGCAAT"
        + "CAGAGACTGTGGATCAAAATTCAGATTCTGATGAAATGCTAGCAATCCTCAAAGAGGTGAG"
        + "CAGGATGAGTCACAGTTCTTCTTCAGATACTGATATTAATGAAATTCATACAAACCATAAG"
        + "ACTTTGTATGATTTAAAGACTCAGGCGGGGAAAGATGATAAAGGAAAAAGGAAACGAAAAA"
        + "GTTCTACATCTGGCTCAGATTTTGATACTAAAAAGGGCAAATCAGCTAAGAGCTCTATAAT"
        + "TTCTAAAAAGAAACGACAAACCCAGTCTGAGTCTTCTAATTATGACTCAGAATTAGAAAAA"
        + "GAGATAAAGAGCATGAGTAAAATTGGTGCTGCCAGAACCACCAAAAAAAGAATTCCAAATA"
        + "CAAAAGATTTTGACTCTTCTGAAGATGAGAAACACAGCAAAAAAGGAATGGATAATCAAGG"
        + "GCACAAAAATTTGAAGACCTCACAAGAAGGATCATCTGATGATGCTGAAAGAAAACAAGAG"
        + "AGAGAGACTTTCTCTTCAGCAGAAGGCACAGTTGATAAAGACACGACCATCATGGAATTAA"
        + "GAGATCGACTTCCTAAGAAGCAGCAAGCAAGTGCTTCCACTGATGGTGTCGATAAGCTTTC"
        + "TGGGAAAGAGCAGAGTTTTACTTCTTTGGAAGTTAGAAAAGTTGCTGAAACTAAAGAAAAG"
        + "AGCAAGCATCTCAAAACCAAAACATGTAAAAAAGTACAGGATGGCTTATCTGATATTGCAG"
        + "AGAAATTCCTAAAGAAAGACCAGAGCGATGAAACTTCTGAAGATGATAAAAAGCAGAGCAA"
        + "AAAGGGAACTGAAGAAAAAAAGAAACCTTCAGACTTTAAGAAAAAAGTAATTAAAATGGAA"
        + "CAACAGTATGAATCTTCATCTGATGGCACTGAAAAGTTACCTGAGCGAGAAGAAATTTGTC"
        + "ATTTTCCTAAGGGCATAAAACAAATTAAGAATGGAACAACTGATGGAGAAAAGAAAAGTAA"
        + "AAAAATAAGAGATAAAACTTCTAAAAAGAAGGATGAATTATCTGATTATGCTGAGAAGTCA"
        + "ACAGGGAAAGGAGATAGTTGTGACTCTTCAGAGGATAAAAAGAGTAAGAATGGAGCATATG"
        + "GTAGAGAGAAGAAAAGGTGCAAGTTGCTTGGAAAGAGTTCAAGGAAGAGACAAGATTGTTC"
        + "ATCATCTGATACTGAGAAATATTCCATGAAAGAAGATGGTTGTAACTCTTCTGATAAGAGA"
        + "CTGAAAAGAATAGAATTGAGGGAAAGAAGAAATTTAAGTTCAAAGAGAAATACTAAGGAAA"
        + "TACAAAGTGGCTCATCATCATCTGATGCTGAGGAAAGTTCTGAAGATAATAAAAAGAAGAA"
        + "GCAAAGAACTTCATCTAAAAAGAAGGCAGTCATTGTCAAGGAGAAAAAGAGAAACTCCCTA"
        + "AGAACAAGCACTAAAAGGAAGCAAGCTGACATTACATCCTCATCTTCTTCTGATATAGAAG"
        + "ATGATGATCAGAATTCTATAGGTGAGGGAAGCAGCGATGAACAGAAAATTAAGCCTGTGAC"
        + "TGAAAATTTAGTGCTGTCTTCACATACTGGATTTTGCCAATCTTCAGGAGATGAAGCCTTA"
        + "TCTAAATCAGTGCCTGTCACAGTGGATGATGATGATGACGACAATGATCCTGAGAATAGAA"
        + "TTGCCAAGAAGATGCTTTTAGAAGAAATTAAAGCCAATCTTTCCTCTGATGAGGATGGATC"
        + "TTCAGATGATGAGCCAGAAGAAGGGAAAAAAAGAACTGGAAAACAAAATGAAGAAAACCCA"
        + "GGAGATGAGGAAGCAAAAAATCAAGTCAATTCTGAATCAGATTCAGATTCTGAAGAATCTA"
        + "AGAAGCCAAGATACAGACATAGGCTTTTGCGGCACAAATTGACTGTGAGTGACGGAGAATC"
        + "TGGAGAAGAAAAAAAGACAAAGCCTAAAGAGCATAAAGAAGTCAAAGGCAGAAACAGAAGA"
        + "AAGGTGAGCAGTGAAGATTCAGAAGATTCTGATTTTCAGGAATCAGGAGTTAGTGAAGAAG"
        + "TTAGTGAATCCGAAGATGAACAGCGGCCCAGAACAAGGTCTGCAAAGAAAGCAGAGTTGGA"
        + "AGAAAATCAGCGGAGCTATAAACAGAAAAAGAAAAGGCGACGTATTAAGGTTCAAGAAGAT"
        + "TCATCCAGTGAAAACAAGAGTAATTCTGAGGAAGAAGAGGAGGAAAAAGAAGAGGAGGAGG"
        + "AAGAGGAGGAGGAGGAGGAAGAGGAGGAGGAAGATGAAAATGATGATTCCAAGTCTCCTGG"
        + "AAAAGGCAGAAAGAAAATTCGGAAGATTCTTAAAGATGATAAACTGAGAACAGAAACACAA"
        + "AATGCTCTTAAGGAAGAGGAAGAGAGACGAAAACGTATTGCTGAGAGGGAGCGTGAGCGAG"
        + "AAAAATTGAGAGAGGTGATAGAAATTGAAGATGCTTCACCCACCAAGTGTCCAATAACAAC"
        + "CAAGTTGGTTTTAGATGAAGATGAAGAAACCAAAGAACCTTTAGTGCAGGTTCATAGAAAT"
        + "ATGGTTATCAAATTGAAACCCCATCAAGTAGATGGTGTTCAGTTTATGTGGGATTGCTGCT"
        + "GTGAGTCTGTGAAAAAAACAAAGAAATCTCCAGGTTCAGGATGCATTCTTGCCCACTGTAT"
        + "GGGCCTTGGTAAGACTTTACAGGTGGTAAGTTTTCTTCATACAGTTCTTTTGTGTGACAAA"
        + "CTGGATTTCAGCACGGCGTTAGTGGTTTGTCCTCTTAATACTGCTTTGAATTGGATGAATG"
        + "AATTTGAGAAGTGGCAAGAGGGATTAAAAGATGATGAGAAGCTTGAGGTTTCTGAATTAGC"
        + "AACTGTGAAACGTCCTCAGGAGAGAAGCTACATGCTGCAGAGGTGGCAAGAAGATGGTGGT"
        + "GTTATGATCATAGGCTATGAGATGTATAGAAATCTTGCTCAAGGAAGGAATGTGAAGAGTC"
        + "GGAAACTTAAAGAAATATTTAACAAAGCTTTGGTTGATCCAGGCCCTGATTTTGTTGTTTG"
        + "TGATGAAGGCCATATTCTAAAAAATGAAGCATCTGCTGTTTCTAAAGCTATGAATTCTATA"
        + "CGATCAAGGAGGAGGATTATTTTAACAGGAACACCACTTCAAAATAACCTAATTGAGTATC"
        + "ATTGTATGGTTAATTTTATCAAGGAAAATTTACTTGGATCCATTAAGGAGTTCAGGAATAG"
        + "ATTTATAAATCCAATTCAAAATGGTCAGTGTGCAGATTCTACCATGGTAGATGTCAGAGTG"
        + "ATGAAAAAACGTGCTCACATTCTCTATGAGATGTTAGCTGGATGTGTTCAGAGGAAAGATT"
        + "ATACAGCATTAACAAAATTCTTGCCTCCAAAACACGAATATGTGTTAGCTGTGAGAATGAC"
        + "TTCTATTCAGTGCAAGCTCTATCAGTACTACTTAGATCACTTAACAGGTGTGGGCAATAAT"
        + "AGTGAAGGTGGAAGAGGAAAGGCAGGTGCAAAGCTTTTCCAAGATTTTCAGATGTTAAGTA"
        + "GAATATGGACTCATCCTTGGTGTTTGCAGCTAGACTACATTAGCAAAGAAAATAAGGGTTA"
        + "TTTTGATGAAGACAGTATGGATGAATTTATAGCCTCAGATTCTGATGAAACCTCCATGAGT"
        + "TTAAGCTCCGATGATTATACAAAAAAGAAGAAAAAAGGGAAAAAGGGGAAAAAAGATAGTA"
        + "GCTCAAGTGGAAGTGGCAGTGACAATGATGTTGAAGTGATTAAGGTCTGGAATTCAAGATC"
        + "TCGGGGAGGTGGTGAAGGAAATGTGGATGAAACAGGAAACAATCCTTCTGTTTCTTTAAAA"
        + "CTGGAAGAAAGTAAAGCTACTTCTTCTTCTAATCCAAGCAGCCCAGCTCCAGACTGGTACA"
        + "AAGATTTTGTTACAGATGCTGATGCTGAGGTTTTAGAGCATTCTGGGAAAATGGTACTTCT"
        + "CTTTGAAATTCTTCGAATGGCAGAGGAAATTGGGGATAAAGTCCTTGTTTTCAGCCAGTCC"
        + "CTCATATCTCTGGACTTGATTGAAGATTTTCTTGAATTAGCTAGTAGGGAGAAGACAGAAG"
        + "ATAAAGATAAACCCCTTATTTATAAAGGTGAGGGGAAGTGGCTTCGAAACATTGACTATTA"
        + "CCGTTTAGATGGTTCCACTACTGCACAGTCAAGGAAGAAGTGGGCTGAAGAATTTAATGAT"
        + "GAAACTAATGTGAGAGGACGATTATTTATCATTTCTACTAAAGCAGGATCTCTAGGAATTA"
        + "ATCTGGTAGCTGCTAATCGAGTAATTATATTCGACGCTTCTTGGAATCCATCTTATGACAT"
        + "CCAGAGTATATTCAGAGTTTATCGCTTTGGACAAACTAAGCCTGTTTATGTATATAGGTTC"
        + "TTAGCTCAGGGAACCATGGAAGATAAGATTTATGATCGGCAAGTAACTAAGCAGTCACTGT"
        + "CTTTTCGAGTTGTTGATCAGCAGCAGGTGGAGCGTCATTTTACTATGAATGAGCTTACTGA"
        + "ACTTTATACTTTTGAGCCAGACTTATTAGATGACCCTAATTCAGAAAAGAAGAAGAAGAGG"
        + "GATACTCCCATGCTGCCAAAGGATACCATACTTGCAGAGCTCCTTCAGATACATAAAGAAC"
        + "ACATTGTAGGATACCATGAACATGATTCTCTTTTGGACCACAAAGAAGAAGAAGAGTTGAC"
        + "TGAAGAAGAAAGAAAAGCAGCTTGGGCTGAGTATGAAGCAGAGAAGAAGGGACTGACCATG"
        + "CGTTTCAACATACCAACTGGGACCAATTTACCCCCTGTCAGTTTCAACTCTCAAACTCCTT"
        + "ATATTCCTTTCAATTTGGGAGCCCTGTCAGCAATGAGTAATCAACAGCTGGAGGACCTCAT"
        + "TAATCAAGGAAGAGAAAAAGTTGTAGAAGCAACAAACAGTGTGACAGCAGTGAGGATTCAA"
        + "CCTCTTGAGGATATAATTTCAGCTGTATGGAAGGAGAACATGAATCTCTCAGAGGCCCAAG"
        + "TACAGGCGTTAGCATTAAGTAGACAAGCCAGCCAGGAGCTTGATGTTAAACGAAGAGAAGC"
        + "AATCTACAATGATGTATTGACAAAACAACAGATGTTAATCAGCTGTGTTCAGCGAATACTT"
        + "ATGAACAGAAGGCTCCAGCAGCAGTACAATCAGCAGCAACAGCAACAAATGACTTATCAAC"
        + "AAGCAACACTGGGTCACCTCATGATGCCAAAGCCCCCAAATTTGATCATGAATCCTTCTAA"
        + "CTACCAGCAGATTGATATGAGAGGAATGTATCAGCCAGTGGCTGGTGGTATGCAGCCACCA"
        + "CCATTACAGCGTGCACCACCCCCAATGAGAAGCAAAAATCCAGGACCTTCCCAAGGGAAAT"
        + "CAATGTGATTTTGCACTAAAAGCTTAATGGATTGTTAAAATCATAGAAAGATCTTTTATTT"
        + "CTTTAGGAATCAATGACTTAACAGAACTCAACTGTATAAATAGTTTGGTCCCCTTAAATGC"
        + "CAATCTTCCATATTAGTTTTACTTTTTTTTTTTTTTAAATAGGGCATACCATTTCTTCCTG"
        + "ACATTTGTCAGTGATGTTGCCTAGAATCTTCTTACACACGCTGAGTACAGAAGATATTTCA"
        + "AATTGTTTTCAGTGAAAACAAGTCCTTCCATAATAGTAACAACTCCACAGATTTCCTCTCT"
        + "AAATTTTTATGCCTGCTTTTAGCAACCATAAAATTGTCATAAAATTAATAAATTTAGGAAA"
        + "GAATAAAGATTTATATATTCATTCTTTACATATAAAAACACACAGCTGAGTTCTTAGAGTT"
        + "GATTCCTCAAGTTATGAAATACTTTTGTACTTAATCCATTTCTTGATTAAAGTGATTGAAA"
        + "TGGTTTTAATGTTCTTTTGACTGAAGTCTGAAACTGGGCTCCTGCTTTATTGTCTCTGTGA"
        + "CTGAAAGTTAGAAACTGAGGGTTATCTTTGACACAGAATTGTGTGCAATATTCTTAAATAC"
        + "TACTGCTCTAAAAGTTGGAGAAGTCTTGCAGTTATCTTAGCATTGTATAAACAGCCTTAAG"
        + "TATAGCCTAAGAAGAGAATTCCTTTTTCTTCTTTAGTCCTTCTGCCATTTTTTATTTTCAG"
        + "TTATATGTGCTGAAATAATTACTGGTAAAATTTCAGGGTTGTGGATTATCTTCCACACATG"
        + "AATTTTCTCTCTCCTGGCACGAATATAAAGCACATCTCTTAACTGCATGGTGCCAGTGCTA"
        + "ATGCTTCATCCTGTTGCTGGCAGTGGGATGTGGACTTAGAAAATCAAGTTCTAGCATTTTA"
        + "GTAGGTTAACACTGAAGTTGTGGTTGTTAGGTTCACACCCTGTTTTATAAACAACATCAAA"
        + "ATGGCAGAACCATTGCTGACTTTAGGTTCACATGAGGAATGTACTTTTAACAATTCCCAGT"
        + "ACTATCAGTATTGTGAAATAATTCCTCTGAAAGATAAGAATCACTGGCTTCTATGCGCTTC"
        + "TTTTCTCTCATCATCATGTTCTTTTACCCCAGTTTCCTTACATTTTTTTAAATTGTTTCAG"
        + "AGTTTGTTTTTTTTTTAGTTTAGATTGTGAGGCAATTATTAAATCAAAATTAATTCATCCA"
        + "ATACCCCTTTACTAGAAGTTTTACTAGAAAATGTATTACATTTTATTTTTTCTTAATCCAG"
        + "TTCTGCAAAAATGACCTATAAATTTATTCATGTACAATTTTGGTTACTTGAATTGTTAAAG"
        + "AAAACATTGTTTTTGACTATGGGAGTCAACTCAACATGGCAGAACCATTTTTGAGATGATG"
        + "ATACAACAGGTAGTGAAACAGCTTAAGAATTCCAAAAAAAAAAAAAAAAAAAAAAAAAAAG"
        + "AAAACTGGGTTTGGGCTTTGCTTTAGGTATCACTGGATTAGAATGAGTTTAACATTAGCTA"
        + "AAACTGCTTTGAGTTGTTTGGATGATTAAGAGATTGCCATTTTTATCTTGGAAGAACTAGT"
        + "GGTAAAACATCCAAGAGCACTAGGATTGTGATACAGAATTTGTGAGGTTTGGTGGATCCAC"
        + "GCCCCTCTCCCCCACTTTCCCATGATGAAATATCACTAATAAATCCTGTATATTTAGATAT"
        + "TATGCTAGCCATGTAATCAGATTTATTTAATTGGGTGGGGCAGGTGTGTATTTACTTTAGA"
        + "AAAAATGAAAAAGACAAGATTTATGAGAAATATTTGAAGGCAGTACACTCTGGCCAACTGT"
        + "TACCAGTTGGTATTTCTACAAGTTCAGAATATTTTAAACCTGATTTACTAGACCTGGGAAT"
        + "TTTCAACATGGTCTAATTATTTACTCAAAGACATAGATGTGAAATTTAGGCAACCTTCTAA"
        + "ATCTTTTCACCATGGATGAAACTATAACTTAAAGATAATACTTAGAAGGGTTAATTGGAAA"
        + "TCAGAGTTTGAAATAAAACTTGGACCACTTTGTATACACTCTTCTCACTTGACATTTTAGC"
        + "TATATAATATGTACTTTGAGTATAACATCAAGCTTTAACAAATATTTAAAGACAAAAAAAT"
        + "CACGTCAGTAAAATACTAAAAGGCTCATTTTTATATTTGTTTTAGATGTTTTAAATAGTTG"
        + "CAATGGATTAAAAATGATGATTTAAAATGTTGCTTGTAATACAGTTTTGCCTGCTAAATTC"
        + "TCCACATTTTGTAACCTGTTTTATTTCTTTGGGTGTAAAGCGTTTTTGCTTAGTATTGTGA"
        + "TATTGTATATGTTTTGTCCCAGTTGTATAGTAATGTTTCAGTCCATCATCCAGCTTTGGCT"
        + "GCTGAAATCATACAGCTGTGAAGACTTGCCTTTGTTTCTGTTAGACTGCTTTTCAGTTCTG"
        + "TATTGAGTATCTTAAGTACTGTAGAAAAGATGTCACTTCTTCCTTTAAGGCTGTTTTGTAA"
        + "TATATATAAGGACTGGAATTGTGTTTTTAAAGAAAAGCATTCAAGTATGACAATATACTAT"
        + "CTGTGTTTTCACCATTCAAAGTGCTGTTTAGTAGTTGAAACTTAAACTATTTAATGTCATT" + "TAATAAAGTGACCAAAATGTG";

    public static final String SEQ_STRING2 = new String(MolComponentTest.SEQ1 + MolComponentTest.SEQ2
        + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3
        + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1
        + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2
        + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3
        + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1
        + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2
        + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3
        + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1
        + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2
        + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3
        + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1
        + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2
        + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3
        + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1
        + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2
        + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3
        + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1
        + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2
        + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3
        + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1
        + MolComponentTest.SEQ2 + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2
        + MolComponentTest.SEQ3 + MolComponentTest.SEQ1 + MolComponentTest.SEQ2 + MolComponentTest.SEQ3
        + "CGAAAACATGACCGCTGAGCCCATGAGTGAAAGCAAGT");

    /**
     * The database being tested
     */
    private final AbstractModel model;

    /**
     * The transaction to use for testing
     */
    private WritableVersion version = null;

    /**
     * @param name
     */
    public MolComponentTest(final String name) {
        super(name);
        this.model = ModelImpl.getModel();
    }

    /**
     * @see junit.framework.TestCase#setUp()
     */
    @Override
    protected void setUp() throws Exception {
        this.version = this.model.getTestVersion();
        Assert.assertNotNull(this.version);
    }

    /**
     * @see junit.framework.TestCase#tearDown()
     */
    @Override
    protected void tearDown() throws Exception {

        Assert.assertFalse(this.version.isCompleted());
        if (this.version.isCompleted()) {
            return; // can't tidy up
        }

        if (null != this.version) {
            this.version.abort(); // not testing persistence
        }

    }

    public void testCreateMolComponent() throws AccessException, ConstraintException {

        final String name = "Test1234";
        Molecule molComponent = null;

        final Map<String, Object> molcompProp = new HashMap<String, Object>();
        molcompProp.put(Substance.PROP_NAME, name);
        molcompProp.put(Molecule.PROP_SEQUENCE, MolComponentTest.SEQ_STRING);
        molcompProp.put(Molecule.PROP_MOLTYPE, "DNA");
        this.version.create(org.pimslims.model.molecule.Molecule.class, molcompProp);

        molComponent =
            this.version.findFirst(org.pimslims.model.molecule.Molecule.class, Substance.PROP_NAME, name);

        Assert.assertEquals(name, molComponent.getName());
        Assert.assertEquals(MolComponentTest.SEQ_STRING, molComponent.getSequence());
    }

}
