
package org.pimslims.ws.client.stubs;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-hudson-$BUILD_NUMBER-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FileUpload", targetNamespace = "http://server.ws.pimslims.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileUpload {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://server.ws.pimslims.org/", className = "org.pimslims.ws.client.stubs.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://server.ws.pimslims.org/", className = "org.pimslims.ws.client.stubs.UploadResponse")
    public void upload(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        DataHandler arg2);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileList", targetNamespace = "http://server.ws.pimslims.org/", className = "org.pimslims.ws.client.stubs.GetFileList")
    @ResponseWrapper(localName = "getFileListResponse", targetNamespace = "http://server.ws.pimslims.org/", className = "org.pimslims.ws.client.stubs.GetFileListResponse")
    public List<String> getFileList();

}
