//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
namespace OPPF.Proxies 
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;
    
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="WSPlateSOAP11Binding", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class WSPlate : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
        
		/// <remarks/>
		public WSPlate() 
		{
            // TODO Move this to the config file
			//this.Url = "http://localhost:8080/axis2/services/WSPlate";
			this.Url = "http://plate.strubi.ox.ac.uk:8080/axis2/services/WSPlate";
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/PlateInfoProvider/getPlateID", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getPlateIDResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public getPlateIDResponse getPlateID([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] getPlateID getPlateIDElement) 
		{
			object[] results = this.Invoke("getPlateID", new object[] {
																		  getPlateIDElement});
			return ((getPlateIDResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetPlateID(getPlateID getPlateIDElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getPlateID", new object[] {
																   getPlateIDElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public getPlateIDResponse EndgetPlateID(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getPlateIDResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/CaptureProvider/getCapturePoints", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getCapturePointsResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public getCapturePointsResponse getCapturePoints([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] getCapturePoints getCapturePointsElement) 
		{
			object[] results = this.Invoke("getCapturePoints", new object[] {
																				getCapturePointsElement});
			return ((getCapturePointsResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetCapturePoints(getCapturePoints getCapturePointsElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getCapturePoints", new object[] {
																		 getCapturePointsElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public getCapturePointsResponse EndgetCapturePoints(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getCapturePointsResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/CaptureProvider/getDefaultCaptureProfile", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getDefaultCaptureProfileResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public getDefaultCaptureProfileResponse getDefaultCaptureProfile([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] getDefaultCaptureProfile getDefaultCaptureProfileElement) 
		{
			object[] results = this.Invoke("getDefaultCaptureProfile", new object[] {
																						getDefaultCaptureProfileElement});
			return ((getDefaultCaptureProfileResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetDefaultCaptureProfile(getDefaultCaptureProfile getDefaultCaptureProfileElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getDefaultCaptureProfile", new object[] {
																				 getDefaultCaptureProfileElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public getDefaultCaptureProfileResponse EndgetDefaultCaptureProfile(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getDefaultCaptureProfileResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/ImagingTaskProvider/updatedPriority", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("updatedPriorityResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public updatedPriorityResponse updatedPriority([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] updatedPriority updatedPriorityElement) 
		{
			object[] results = this.Invoke("updatedPriority", new object[] {
																			   updatedPriorityElement});
			return ((updatedPriorityResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginupdatedPriority(updatedPriority updatedPriorityElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("updatedPriority", new object[] {
																		updatedPriorityElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public updatedPriorityResponse EndupdatedPriority(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((updatedPriorityResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/PlateInfoProvider/getPlateInfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getPlateInfoResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public getPlateInfoResponse getPlateInfo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] getPlateInfo getPlateInfoElement) 
		{
			object[] results = this.Invoke("getPlateInfo", new object[] {
																			getPlateInfoElement});
			return ((getPlateInfoResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetPlateInfo(getPlateInfo getPlateInfoElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getPlateInfo", new object[] {
																	 getPlateInfoElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public getPlateInfoResponse EndgetPlateInfo(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getPlateInfoResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/PlateInfoProvider/getPlateTypes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getPlateTypesResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public getPlateTypesResponse getPlateTypes([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] getPlateTypes getPlateTypesElement) 
		{
			object[] results = this.Invoke("getPlateTypes", new object[] {
																			 getPlateTypesElement});
			return ((getPlateTypesResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetPlateTypes(getPlateTypes getPlateTypesElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getPlateTypes", new object[] {
																	  getPlateTypesElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public getPlateTypesResponse EndgetPlateTypes(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getPlateTypesResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/ImagingTaskProvider/imagingPlate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("imagingPlateResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public imagingPlateResponse imagingPlate([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] imagingPlate imagingPlateElement) 
		{
			object[] results = this.Invoke("imagingPlate", new object[] {
																			imagingPlateElement});
			return ((imagingPlateResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginimagingPlate(imagingPlate imagingPlateElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("imagingPlate", new object[] {
																	 imagingPlateElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public imagingPlateResponse EndimagingPlate(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((imagingPlateResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/ImagingTaskProvider/imagedPlate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("imagedPlateResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public imagedPlateResponse imagedPlate([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] imagedPlate imagedPlateElement) 
		{
			object[] results = this.Invoke("imagedPlate", new object[] {
																		   imagedPlateElement});
			return ((imagedPlateResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginimagedPlate(imagedPlate imagedPlateElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("imagedPlate", new object[] {
																	imagedPlateElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public imagedPlateResponse EndimagedPlate(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((imagedPlateResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/ImagingTaskProvider/getImagingTasks", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getImagingTasksResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public getImagingTasksResponse getImagingTasks([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] getImagingTasks getImagingTasksElement) 
		{
			object[] results = this.Invoke("getImagingTasks", new object[] {
																			   getImagingTasksElement});
			return ((getImagingTasksResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetImagingTasks(getImagingTasks getImagingTasksElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getImagingTasks", new object[] {
																		getImagingTasksElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public getImagingTasksResponse EndgetImagingTasks(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getImagingTasksResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/ImageProcessorProvider/getImageProcessor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getImageProcessorResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public getImageProcessorResponse getImageProcessor([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] getImageProcessor getImageProcessorElement) 
		{
			object[] results = this.Invoke("getImageProcessor", new object[] {
																				 getImageProcessorElement});
			return ((getImageProcessorResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetImageProcessor(getImageProcessor getImageProcessorElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getImageProcessor", new object[] {
																		  getImageProcessorElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public getImageProcessorResponse EndgetImageProcessor(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getImageProcessorResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/PlateInfoProvider/getPlateType", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getPlateTypeResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public getPlateTypeResponse getPlateType([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] getPlateType getPlateTypeElement) 
		{
			object[] results = this.Invoke("getPlateType", new object[] {
																			getPlateTypeElement});
			return ((getPlateTypeResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetPlateType(getPlateType getPlateTypeElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getPlateType", new object[] {
																	 getPlateTypeElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public getPlateTypeResponse EndgetPlateType(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getPlateTypeResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/ImagingTaskProvider/supportsPriority", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("supportsPriorityResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public supportsPriorityResponse supportsPriority([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] supportsPriority supportsPriorityElement) 
		{
			object[] results = this.Invoke("supportsPriority", new object[] {
																				supportsPriorityElement});
			return ((supportsPriorityResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginsupportsPriority(supportsPriority supportsPriorityElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("supportsPriority", new object[] {
																		 supportsPriorityElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public supportsPriorityResponse EndsupportsPriority(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((supportsPriorityResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/CaptureProvider/getFirstDrop", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getFirstDropResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public getFirstDropResponse getFirstDrop([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] getFirstDrop getFirstDropElement) 
		{
			object[] results = this.Invoke("getFirstDrop", new object[] {
																			getFirstDropElement});
			return ((getFirstDropResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BegingetFirstDrop(getFirstDrop getFirstDropElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getFirstDrop", new object[] {
																	 getFirstDropElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public getFirstDropResponse EndgetFirstDrop(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getFirstDropResponse)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.oppf.ox.ac.uk/WSPlate/ImagingTaskProvider/skippedImaging", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("skippedImagingResponseElement", Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
		public skippedImagingResponse skippedImaging([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")] skippedImaging skippedImagingElement) 
		{
			object[] results = this.Invoke("skippedImaging", new object[] {
																			  skippedImagingElement});
			return ((skippedImagingResponse)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginskippedImaging(skippedImaging skippedImagingElement, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("skippedImaging", new object[] {
																	   skippedImagingElement}, callback, asyncState);
		}
        
		/// <remarks/>
		public skippedImagingResponse EndskippedImaging(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((skippedImagingResponse)(results[0]));
		}
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getPlateID 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string barcode;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class Robot 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string iD;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string name;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class skippedImagingResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool skippedPlateReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class skippedImaging 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.DateTime dateToImage;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class GetFirstDropReturn 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int wellNumber;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int dropNumber;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getFirstDropResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public GetFirstDropReturn getFirstDropReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getFirstDrop 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int wellNumber;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int dropNumber;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class supportsPriorityResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool supportsPriorityReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class supportsPriority 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getPlateTypeResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public PlateType getPlateTypeReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class PlateType 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string iD;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string name;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int numColumns;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int numDrops;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int numRows;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getPlateType 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateTypeID;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getImageProcessorResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
		public PlateType[] wrapper;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getImageProcessor 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class ImagingTask 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int state;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.DateTime dateImaged;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int priority;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.DateTime dateToImage;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool inQueue;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getImagingTasksResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
		public ImagingTask[] wrapper;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getImagingTasks 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateID;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class imagedPlateResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool imagedPlateReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class imagedPlate 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string imagingID;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class imagingPlateResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string imagingPlateReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class imagingPlate 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool scheduled;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.DateTime dateToImage;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.DateTime dateImaged;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getPlateTypesResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
		public PlateType[] wrapper;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getPlateTypes 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class PlateInfo 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.DateTime dateDispensed;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string experimentName;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int plateNumber;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateTypeID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string projectName;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string userEmail;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string userName;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getPlateInfoResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public PlateInfo getPlateInfoReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getPlateInfo 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateID;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class updatedPriorityResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool updatedPriorityReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class updatedPriority 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.DateTime dateToImage;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int priority;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getDefaultCaptureProfileResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CaptureProfile getDefaultCaptureProfileReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class CaptureProfile 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string profileID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
		public Property[] properties;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class Property 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string name;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string value;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getDefaultCaptureProfile 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateID;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class Size 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.Single height;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.Single width;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class Point 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.Single x;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.Single y;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public System.Single z;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class CapturePoint 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Point center;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool isAbsolute;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int regionType;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string regionID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
		public CaptureProfile[] captureProfiles;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Size size;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int dropNumber;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public int wellNumber;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CapturePoint parent;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class CapturePointList 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CaptureProfile plateCaptureProfile;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
		public CapturePoint[] capturePoints;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CaptureProfile dropLocationProfile;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getCapturePointsResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public CapturePointList getCapturePointsReturn;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getCapturePoints 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Robot robot;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string plateID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string imagingID;
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool includeOverview;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/WSPlate/")]
	public class getPlateIDResponse 
	{
        
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string getPlateIDReturn;
	}
}
