create table ACCO_PERMISSION (OPTYPE varchar(32) not null, PERMISSION BOOLEAN not null, PERMISSIONCLASS varchar(32) not null, ROLENAME varchar(32) not null, SYSTEMCLASSID int8 not null, ACCESSOBJECTID int8 not null, USERGROUPID int8 not null, primary key (SYSTEMCLASSID), unique (OPTYPE, ACCESSOBJECTID, USERGROUPID));
create table ACCO_PREFERENCE (NAME varchar(80) not null unique, VALUE varchar(255), SYSTEMCLASSID int8 not null, USERID int8, primary key (SYSTEMCLASSID));
create table ACCO_USER (DIGESTEDPASSWORD varchar(255), isActive BOOLEAN, NAME varchar(80) not null unique, SYSTEMCLASSID int8 not null, PERSONID int8, SUPERVISORID int8, primary key (SYSTEMCLASSID));
create table ACCO_USERGROUP (maxSize INTEGER, NAME varchar(80) not null unique, SYSTEMCLASSID int8 not null, HEADERID int8, primary key (SYSTEMCLASSID));
create table ACCO_USERGROUP2USER (USERGROUPID int8 not null, MEMBERUSERID int8 not null, primary key (USERGROUPID, MEMBERUSERID));
create table CORE_ACCESSOBJECT (NAME varchar(80) not null unique, SYSTEMCLASSID int8 not null, primary key (SYSTEMCLASSID));
create table CORE_ANNOTATION (FILENAME varchar(254), LEGEND TEXT, MIMETYPE varchar(80), NAME varchar(80), TITLE varchar(254), ATTACHMENTID int8 not null, primary key (ATTACHMENTID));
create table CORE_APPLICATIONDATA (APPLICATION varchar(80) not null, KEYWORD varchar(80) not null, TYPE varchar(80), VALUE TEXT not null, ATTACHMENTID int8 not null, primary key (ATTACHMENTID));
create table CORE_ATTACHMENT (DBID int8 not null, DATE_ TIMESTAMPTZ, DETAILS TEXT, AUTHORID int8, PARENTENTRYID int8 not null, primary key (DBID));
create table CORE_BOOKCITATION (BOOKSERIES varchar(254), BOOKTITLE varchar(254), ISBN varchar(80), PUBLISHER varchar(254), PUBLISHERCITY varchar(254), VOLUME varchar(80), CITATIONID int8 not null, primary key (CITATIONID));
create table CORE_BOOKMARK (NAME varchar(80) not null unique, URL TEXT not null, LabBookEntryID int8 not null, primary key (LabBookEntryID));
create table CORE_CITATION (AUTHORS TEXT, EDITORS TEXT, FIRSTPAGE varchar(80), LASTPAGE varchar(80), STATUS varchar(80), TITLE TEXT, YEAR INTEGER, ATTACHMENTID int8 not null, primary key (ATTACHMENTID));
create table CORE_CONFERENCECITATION (ABSTRACTNUMBER varchar(80), CITY varchar(80), CONFERENCESITE varchar(80), CONFERENCETITLE varchar(254), COUNTRY varchar(80), ENDDATE TIMESTAMPTZ, STARTDATE TIMESTAMPTZ, STATEPROVINCE varchar(80), CITATIONID int8 not null, primary key (CITATIONID));
create table CORE_EXTERNALDBLINK (CODE varchar(80), RELEASE varchar(80), URL TEXT, ATTACHMENTID int8 not null, DBNAMEID int8 not null, primary key (ATTACHMENTID));
create table CORE_JOURNALCITATION (ASTM varchar(80), CSD varchar(80), ISSN varchar(80), ISSUE varchar(80), JOURNALABBREVIATION varchar(80), JOURNALFULLNAME varchar(254), VOLUME varchar(80), CITATIONID int8 not null, primary key (CITATIONID));
create table CORE_LABBOOKENTRY (DBID int8 not null, CREATIONDATE TIMESTAMPTZ, DETAILS TEXT, LASTEDITEDDATE TIMESTAMPTZ, PAGENUMBER TEXT, ACCESSID int8, CREATORID int8, LASTEDITORID int8, primary key (DBID));
create table CORE_NOTE (NAME varchar(80), ATTACHMENTID int8 not null, primary key (ATTACHMENTID));
create table CORE_NOTE2RELATEDENTRYS (NOTEID int8 not null, LABBOOKENTRYID int8 not null, primary key (NOTEID, LABBOOKENTRYID));
create table CORE_SYSTEMCLASS (DBID int8 not null, DETAILS TEXT, primary key (DBID));
create table CORE_THESISCITATION (CITY varchar(80), COUNTRY varchar(80), INSTITUTION varchar(254), STATEPROVINCE varchar(80), CITATIONID int8 not null, primary key (CITATIONID));
create table CRYZ_DROPANNOTATION (CMDLINEPARAM TEXT, SCOREDATE TIMESTAMPTZ, LabBookEntryID int8 not null, HOLDERID int8, IMAGEID int8, SAMPLEID int8, SCOREID int8 not null, SOFTWAREID int8, primary key (LabBookEntryID));
create table CRYZ_IMAGE (FILENAME varchar(254) not null, FILEPATH varchar(254) not null, MIMETYPE varchar(80), LabBookEntryID int8 not null, IMAGETYPEID int8, INSTRUMENTID int8, SAMPLEID int8, SCHEDULEDTASKID int8, WELLIMAGETYPEID int8, primary key (LabBookEntryID));
create table CRYZ_PARAMETER (VALUE varchar(254), LabBookEntryID int8 not null, PARAMETERDEFINITIONID int8 not null, IMAGEID int8 not null, primary key (LabBookEntryID));
create table CRYZ_PARAMETERDEFINITION (DEFAULTVALUE varchar(80), DISPLAYUNIT varchar(32), LABEL TEXT, MAXVALUE varchar(80), MINVALUE varchar(80), NAME varchar(80) unique, PARAMTYPE varchar(32), UNIT varchar(32), LabBookEntryID int8 not null, primary key (LabBookEntryID));
create table CRYZ_SCORE (color varchar(80), NAME varchar(80), VALUE INTEGER not null, LabBookEntryID int8 not null, SCORINGSCHEMEID int8 not null, primary key (LabBookEntryID), unique (VALUE, SCORINGSCHEMEID));
create table CRYZ_SCORINGSCHEME (NAME varchar(80) not null unique, VERSION varchar(80), LabBookEntryID int8 not null, primary key (LabBookEntryID));
create table CRYZ_WELLIMAGETYPE (CATEGORY varchar(180), COLOURDEPTH INTEGER, NAME varchar(80) not null unique, SIZEX INTEGER, SIZEY INTEGER, URL varchar(180), XLENGTHPERPIXEL FLOAT8, YLENGTHPERPIXEL FLOAT8, LabBookEntryID int8 not null, primary key (LabBookEntryID));
create table EXPE_EXPERIMENT (ENDDATE TIMESTAMPTZ not null, INVOICENUMBER varchar(1024), ISLOCKED BOOLEAN, NAME varchar(80) not null unique, STARTDATE TIMESTAMPTZ not null, STATUS varchar(32), LabBookEntryID int8 not null, EXPERIMENTGROUPID int8, EXPERIMENTTYPEID int8 not null, GROUPID int8, INSTRUMENTID int8, METHODID int8, OPERATORID int8, PROTOCOLID int8, RESEARCHOBJECTIVEID int8, primary key (LabBookEntryID));
create table EXPE_EXPERIMENTGROUP (ENDDATE TIMESTAMPTZ, NAME varchar(80) not null unique, PURPOSE varchar(80) not null, STARTDATE TIMESTAMPTZ, LabBookEntryID int8 not null, primary key (LabBookEntryID));
create table EXPE_INPUTSAMPLE (AMOUNT FLOAT8, AMOUNTDISPLAYUNIT varchar(32), AMOUNTUNIT varchar(32), NAME varchar(80), ROLE varchar(80), LabBookEntryID int8 not null, EXPERIMENTID int8 not null, REFINPUTSAMPLEID int8, SAMPLEID int8, order_ int4, primary key (LabBookEntryID));
create table EXPE_INSTRUMENT (FILEPATH varchar(1024), MODEL varchar(80), NAME varchar(80) not null unique, PRESSURE FLOAT8, PRESSUREDISPLAYUNIT varchar(32), SERIALNUMBER varchar(80), TEMPDISPLAYUNIT varchar(32), TEMPERATURE FLOAT8, LabBookEntryID int8 not null, DEFAULTIMAGETYPEID int8, DEFAULTWELLIMAGETYPEID int8, LOCATIONID int8, MANUFACTURERID int8, primary key (LabBookEntryID));
create table EXPE_METHOD (NAME varchar(80) unique, PROCEDURE_ TEXT, TASK varchar(80), LabBookEntryID int8 not null, INSTRUMENTID int8, SOFTWAREID int8, primary key (LabBookEntryID));
create table EXPE_METHODPARAMETER (NAME varchar(80) not null, PARAMTYPE varchar(32), UNIT varchar(32), VALUE varchar(254), LabBookEntryID int8 not null, METHODID int8 not null, primary key (LabBookEntryID));
create table EXPE_OUTPUTSAMPLE (AMOUNT FLOAT8, AMOUNTDISPLAYUNIT varchar(32), AMOUNTUNIT varchar(32), NAME varchar(80), ROLE varchar(80), LabBookEntryID int8 not null, EXPERIMENTID int8 not null, REFOUTPUTSAMPLEID int8, SAMPLEID int8 unique, primary key (LabBookEntryID));
create table EXPE_PARAMETER (NAME varchar(80), PARAMTYPE varchar(32), UNIT varchar(32), VALUE TEXT, LabBookEntryID int8 not null, EXPERIMENTID int8 not null, PARAMETERDEFINITIONID int8, primary key (LabBookEntryID));
create table EXPE_SOFTWARE (NAME varchar(80) not null unique, VENDORADDRESS varchar(254), VENDORNAME varchar(254), VENDORWEBADDRESS TEXT, VERSION varchar(80) not null, LabBookEntryID int8 not null, primary key (LabBookEntryID), unique (NAME, VERSION));
create table EXPE_SOFTWARE_TASKS (SOFTWAREID int8 not null, TASK varchar(255), ORDER_ int4 not null, primary key (SOFTWAREID, ORDER_));
create table EXPE_WORKFLOW (NAME varchar(80) not null unique, LabBookEntryID int8 not null, primary key (LabBookEntryID));
create table EXPE_WORKFLOW2PROTOCOLS (WORKFLOWID int8 not null, PROTOCOLID int8 not null, primary key (WORKFLOWID, PROTOCOLID));
create table EXPE_WORKFLOW2RESEARCHOBJECTIVE (WORKFLOWID int8 not null, PROJECTID int8 not null, primary key (WORKFLOWID, PROJECTID));
create table HOLD_ABSTRACTHOLDER (COLPOSITION INTEGER, NAME varchar(80) not null unique, ROWPOSITION INTEGER, SUBPOSITION INTEGER, LabBookEntryID int8 not null, HOLDERTYPEID int8, ABSTRACTHOLDERID int8, primary key (LabBookEntryID));
create table HOLD_HOLDER (CRYSTALNUMBER INTEGER, ENDDATE TIMESTAMPTZ, STARTDATE TIMESTAMPTZ, ABSTRACTHOLDERID int8 not null, FIRSTSAMPLEID int8, LASTTASKID int8, primary key (ABSTRACTHOLDERID));
create table HOLD_HOLDERLOCATION (ENDDATE TIMESTAMPTZ, STARTDATE TIMESTAMPTZ not null, LabBookEntryID int8 not null, HOLDERID int8 not null, LOCATIONID int8 not null, primary key (LabBookEntryID));
create table HOLD_HOLDERTYPEPOSITION (COLPOSITION INTEGER, MAXVOLUME FLOAT8, MAXVOLUMEDIPLAYUNIT varchar(32), NAME varchar(32), ROWPOSITION INTEGER, SUBPOSITION INTEGER, LabBookEntryID int8 not null, HOLDERTYPEID int8 not null, primary key (LabBookEntryID));
create table HOLD_REFHOLDER (ABSTRACTHOLDERID int8 not null, primary key (ABSTRACTHOLDERID));
create table HOLD_REFHOLDEROFFSET (COLOffset INTEGER, ROWOffset INTEGER, SUBOffset INTEGER, LabBookEntryID int8 not null, HOLDERID int8 not null, REFHOLDERID int8 not null, primary key (LabBookEntryID), unique (ROWOffset, COLOffset, SUBOffset, HOLDERID));
create table HOLD_REFHOLDERSOURCE (CATALOGNUM varchar(80) not null, DATAPAGEURL varchar(254), PRODUCTGROUPNAME varchar(254), PRODUCTNAME varchar(254), LabBookEntryID int8 not null, REFHOLDERID int8 not null, SUPPLIERID int8 not null, primary key (LabBookEntryID), unique (CATALOGNUM, REFHOLDERID));
create table HOLD_REFSAMPLEPOSITION (COLPOSITION INTEGER, ROWPOSITION INTEGER, SUBPOSITION INTEGER, LabBookEntryID int8 not null, RefHOLDERID int8 not null, REFSAMPLEID int8, primary key (LabBookEntryID), unique (ROWPOSITION, COLPOSITION, SUBPOSITION, RefHOLDERID));
create table LOCA_LOCATION (LOCATIONTYPE varchar(80), NAME varchar(80) not null unique, PRESSURE FLOAT8, PRESSUREDISPLAYUNIT varchar(32), TEMPDISPLAYUNIT varchar(32), TEMPERATURE FLOAT8, LabBookEntryID int8 not null, LOCATIONID int8, ORGANISATIONID int8, primary key (LabBookEntryID));
create table MOLE_ABSTCO_KEYWORDS (ABSTRACTCOMPONENTID int8 not null, KEYWORD varchar(255), ORDER_ int4 not null, primary key (ABSTRACTCOMPONENTID, ORDER_));
create table MOLE_ABSTCO_SYNONYMS (ABSTRACTCOMPONENTID int8 not null, SYNONYM_ varchar(255), ORDER_ int4 not null, primary key (ABSTRACTCOMPONENTID, ORDER_));
create table MOLE_ABSTRACTCOMPONENT (NAME varchar(80) not null unique, LabBookEntryID int8 not null, NATURALSOURCEID int8, primary key (LabBookEntryID));
create table MOLE_COMPCA2COMPONENTS (COMPONENTID int8 not null, CATEGORYID int8 not null, primary key (COMPONENTID, CATEGORYID));
create table MOLE_CONSTRUCT (CONSTRUCTSTATUS varchar(80), FUNCTION TEXT, MARKERDETAILS TEXT, PROMOTERDETAILS TEXT, RESISTANCEDETAILS TEXT, SEQUENCETYPE varchar(80), MOLECULEID int8 not null, primary key (MOLECULEID));
create table MOLE_EXTENSION (EXTENSIONTYPE varchar(32) not null, ISFORUSE BOOLEAN, RELATEDPROTEINTAGSEQ TEXT, RESTRICTIONENZYME varchar(254), MOLECULEID int8 not null, primary key (MOLECULEID));
create table MOLE_HOST (ANTIBIOTICRESISTANCES varchar(254), COMMENTS TEXT, GENOTYPE varchar(254), HARBOUREDPLASMIDS varchar(254), SELECTABLEMARKERS varchar(254), STRAIN varchar(80), USE varchar(254), SUBSTANCEID int8 not null, primary key (SUBSTANCEID));
create table MOLE_HOST2ORGANISATION (HOSTID int8 not null, ORGANISATIONID int8 not null, primary key (HOSTID, ORGANISATIONID));
create table MOLE_MOLECULE (CASNUM varchar(32), EMPIRICALFORMULA varchar(80), ISVOLATILE BOOLEAN, MOLTYPE varchar(80) not null, MOLECULARMASS FLOAT8, SEQDETAILS TEXT, SEQSTRING TEXT, SUBSTANCEID int8 not null, primary key (SUBSTANCEID));
create table MOLE_MOLECULE2RELAREOBEL (RELATEDROELEMENTID int8 not null, TRIALMOLECULEID int8 not null, primary key (RELATEDROELEMENTID, TRIALMOLECULEID));
create table MOLE_MOLECULEFEATURE (ENDSEQID INTEGER, FEATURETYPE varchar(80) not null, NAME varchar(80) not null, ORDERING INTEGER, STARTSEQID INTEGER, STATUS varchar(80), LabBookEntryID int8 not null, MOLECULEID int8 not null, REFMOLECULEID int8, primary key (LabBookEntryID));
create table MOLE_PRIMER (DIRECTION varchar(32) not null, GCGENE varchar(80), ISUNIVERSAL BOOLEAN not null, LENGTHONGENE INTEGER, MELTINGTEMPERATURE FLOAT8, MELTINGTEMPERATUREGENE FLOAT8, MELTINGTEMPERATURESELLER FLOAT8, OPTICALDENSITY varchar(32), PARTICULARITY TEXT, RESTRICTIONSITE TEXT, MOLECULEID int8 not null, primary key (MOLECULEID));
create table PEOP_GROUP (NAME varchar(80), URL varchar(254), LabBookEntryID int8 not null, ORGANISATIONID int8 not null, primary key (LabBookEntryID));
create table PEOP_ORGANISATION (CITY varchar(80), COUNTRY varchar(80), EMAILADDRESS varchar(80), FAXNUMBER varchar(80), NAME varchar(80) not null unique, ORGANISATIONTYPE varchar(80), PHONENUMBER varchar(80), POSTALCODE varchar(80), URL varchar(254), LabBookEntryID int8 not null, primary key (LabBookEntryID));
create table PEOP_ORGA_ADDRESSES (ORGANISATIONID int8 not null, ADDRESS varchar(255), ORDER_ int4 not null, primary key (ORGANISATIONID, ORDER_));
create table PEOP_PERSINGR_PHONNU (PERSONINGROUPID int8 not null, PHONENUMBER varchar(255), order_ int4 not null, primary key (PERSONINGROUPID, order_));
create table PEOP_PERSON (FAMILYNAME varchar(80) not null, FAMILYTITLE varchar(32), GIVENNAME varchar(80), TITLE varchar(80), LabBookEntryID int8 not null, CURRENTGROUPID int8, primary key (LabBookEntryID));
create table PEOP_PERSONINGROUP (DELIVERYADDRESS varchar(254), EMAILADDRESS varchar(80), ENDDATE TIMESTAMPTZ, FAXNUMBER varchar(80), MAILINGADDRESS varchar(254), POSITION_ varchar(80), STARTDATE TIMESTAMPTZ, LabBookEntryID int8 not null, GROUPID int8 not null, PERSONID int8 not null, primary key (LabBookEntryID));
create table PEOP_PERSON_MIDDIN (PERSONID int8 not null, MIDDLEINITIAL varchar(255), ORDER_ int4 not null, primary key (PERSONID, ORDER_));
create table PROT_PARADE_POSSVA (PARAMETERDEFINITIONID int8 not null, POSSIBLEVALUE varchar(255), ORDER_ int4 not null, primary key (PARAMETERDEFINITIONID, ORDER_));
create table PROT_PARAMETERDEFINITION (DEFAULTVALUE varchar(80), DISPLAYUNIT varchar(32), ISGROUPLEVEL BOOLEAN not null, ISMANDATORY BOOLEAN not null, ISRESULT BOOLEAN not null, LABEL TEXT, MAXVALUE varchar(80), MINVALUE varchar(80), NAME varchar(80) not null, PARAMTYPE varchar(32) not null, UNIT varchar(32), LabBookEntryID int8 not null, PROTOCOLID int8 not null, order_ int4, primary key (LabBookEntryID), unique (NAME, PROTOCOLID));
create table PROT_PROTOCOL (ISFORUSE BOOLEAN not null, METHODDESCRIPTION TEXT, NAME varchar(80) not null unique, OBJECTIVE varchar(254), LabBookEntryID int8 not null, EXPERIMENTTYPEID int8 not null, INSTRUMENTTYPEID int8, primary key (LabBookEntryID));
create table PROT_PROTOCOL_REMARKS (PROTOCOLID int8 not null, REMARK varchar(255), ORDER_ int4 not null, primary key (PROTOCOLID, ORDER_));
create table PROT_REFINPUTSAMPLE (AMOUNT FLOAT8, DISPLAYUNIT varchar(32), NAME varchar(80), UNIT varchar(32), LabBookEntryID int8 not null, PROTOCOLID int8 not null, RECIPEID int8, SAMPLECATEGORYID int8 not null, order_ int4, primary key (LabBookEntryID), unique (PROTOCOLID, NAME));
create table PROT_REFOUTPUTSAMPLE (AMOUNT FLOAT8, DISPLAYUNIT varchar(32), NAME varchar(80), UNIT varchar(32), LabBookEntryID int8 not null, PROTOCOLID int8 not null, SAMPLECATEGORYID int8 not null, primary key (LabBookEntryID), unique (PROTOCOLID, NAME));
create table REF_ABSTRACTHOLDERTYPE (NAME varchar(80) not null unique, PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_COMPONENTCATEGORY (NAME varchar(80) not null unique, PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_CRYSTALTYPE (ResSubPos INTEGER not null, HOLDERTYPEID int8 not null, primary key (HOLDERTYPEID));
create table REF_DBNAME (FULLNAME TEXT, NAME varchar(80) not null unique, URL TEXT, PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_EXPERIMENTTYPE (NAME varchar(80) not null unique, PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_HAZARDPHRASE (CLASSIFICATION varchar(32) not null, CODE varchar(80) not null, PHRASE varchar(254), PublicEntryID int8 not null, primary key (PublicEntryID), unique (CLASSIFICATION, CODE));
create table REF_HOLDERCATEGORY (NAME varchar(80) not null unique, PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_HOLDERTYPE (HOLDHOLDERFLAG BOOLEAN, MAXCOLUMN INTEGER, MAXROW INTEGER, MAXSUBPOSITION INTEGER, MAXVOLUME FLOAT8, MAXVOLUMEDISPLAYUNIT varchar(32), ABSTRACTHOLDERTYPEID int8 not null, DefaultSchedulePlanID int8, primary key (ABSTRACTHOLDERTYPEID));
create table REF_HOLDERTYPESOURCE (CATALOGNUM varchar(80) not null, DATAPAGEURL varchar(254), PRODUCTNAME varchar(254), PublicEntryID int8 not null, HOLDERTYPEID int8 not null, SUPPLIERID int8 not null, primary key (PublicEntryID), unique (CATALOGNUM, HOLDERTYPEID));
create table REF_IMAGETYPE (CATORGORY varchar(180), COLOURDEPTH INTEGER, NAME varchar(80) not null unique, SIZEX INTEGER, SIZEY INTEGER, URL varchar(180), XLENGTHPERPIXEL FLOAT8, YLENGTHPERPIXEL FLOAT8, PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_INSTRUMENTTYPE (NAME varchar(80) not null unique, PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_ORGANISM (ATCCNUMBER varchar(80), CELLLINE varchar(80), CELLLOCATION TEXT, CELLTYPE varchar(80), FRACTION varchar(254), GENEMNEMONIC varchar(254), GENUS varchar(80), ICTVCODE varchar(254), NAME varchar(80) not null unique, NCBITAXONOMYID varchar(254), ORGAN varchar(80), ORGANELLE varchar(254), ORGANISMACRONYM varchar(254), PLASMID varchar(254), PLASMIDDETAILS TEXT, SCIENTIFICNAME varchar(80), SECRETION TEXT, SPECIES varchar(80), STRAIN varchar(80), SUBVARIANT varchar(254), TISSUE varchar(80), VARIANT varchar(80), PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_PINTYPE (LENGTH FLOAT8, LOOPLENGTH FLOAT8, LOOPTYPE varchar(80), WIREWIDTH FLOAT8, ABSTRACTHOLDERTYPEID int8 not null, primary key (ABSTRACTHOLDERTYPEID));
create table REF_PUBLICENTRY (DBID int8 not null, DETAILS TEXT, primary key (DBID));
create table REF_SAMPLECATEGORY (NAME varchar(80) not null unique, PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_TARGETSTATUS (NAME varchar(80) not null unique, PublicEntryID int8 not null, primary key (PublicEntryID));
create table REF_WORKFLOWITEM (PublicEntryID int8 not null, EXPERIMENTTYPEID int8 not null, STATUSID int8, primary key (PublicEntryID));
create table SAM_ABSTRACTSAMPLE (IONICSTRENGTH FLOAT8, ISACTIVE BOOLEAN, ISHAZARD BOOLEAN, NAME varchar(80) not null unique, PH FLOAT8, LabBookEntryID int8 not null, primary key (LabBookEntryID));
create table SAM_ABSTSA2HAZAPH (OTHERROLE int8 not null, HAZARDPHRASEID int8 not null, primary key (OTHERROLE, HAZARDPHRASEID));
create table SAM_CRYSTALSAMPLE (A FLOAT8, ALPHA FLOAT8, B FLOAT8, BETA FLOAT8, C FLOAT8, COLOUR varchar(254), CRYSTALTYPE varchar(254), GAMMA FLOAT8, MORPHOLOGY varchar(254), SPACEGROUP varchar(32), X FLOAT8, Y FLOAT8, Z FLOAT8, SAMPLEID int8 not null, primary key (SAMPLEID));
create table SAM_REFSAMPLE (isSaltCrystal BOOLEAN, ABSTRACTSAMPLEID int8 not null, primary key (ABSTRACTSAMPLEID));
create table SAM_REFSAMPLESOURCE (CATALOGNUM varchar(80) not null, DATAPAGEURL varchar(254), PRODUCTGROUPNAME varchar(254), PRODUCTNAME varchar(254), LabBookEntryID int8 not null, REFSAMPLEID int8 not null, SUPPLIERID int8 not null, primary key (LabBookEntryID), unique (CATALOGNUM, REFSAMPLEID));
create table SAM_SAMPLE (AMOUNTDISPLAYUNIT varchar(32), AMOUNTUNIT varchar(32), BATCHNUM varchar(32), COLPOSITION INTEGER, CONCDISPLAYUNIT varchar(32), CONCENTRATION FLOAT8, CONCENTRATIONUNIT varchar(32), CURRENTAMOUNT FLOAT8, CURRENTAMOUNTFLAG BOOLEAN, INITIALAMOUNT FLOAT8, INVOICENUMBER varchar(1024), ROWPOSITION INTEGER, SUBPOSITION INTEGER, USEBYDATE TIMESTAMPTZ, ABSTRACTSAMPLEID int8 not null, ASSIGNTOID int8, HOLDERID int8, REFSAMPLEID int8, primary key (ABSTRACTSAMPLEID));
create table SAM_SAMPLECOMPONENT (CONCDISPLAYUNIT varchar(32), CONCENTRATION FLOAT8, CONCENTRATIONERROR FLOAT8, CONCENTRATIONUNIT varchar(32), PH FLOAT8, PURITY FLOAT8, LabBookEntryID int8 not null, ABSTRACTSAMPLEID int8 not null, CONTAINERID int8, REFCOMPONENTID int8 not null, RESEARCHOBJECTIVELEMENTID int8, primary key (LabBookEntryID));
create table SCHE_SCHEDULEDTASK (COMPLETIONTIME TIMESTAMP WITH TIME ZONE, NAME varchar(80) not null unique, Priority INTEGER, SCHEDULEDTIME TIMESTAMP not null, STATE INTEGER, LabBookEntryID int8 not null, HOLDERID int8 not null, INSTRUMENTID int8, SchedulePlanOffsetID int8, primary key (LabBookEntryID), unique (SCHEDULEDTIME, HOLDERID));
create table SCHE_SCHEDULEPLAN (NAME varchar(80) not null unique, LabBookEntryID int8 not null, primary key (LabBookEntryID));
create table SCHE_SCHEDULEPLANOFFSET (OffsetTime int8 not null, Priority INTEGER, LabBookEntryID int8 not null, SchedulePlanID int8 not null, order_ int4, primary key (LabBookEntryID), unique (OffsetTime, SchedulePlanID));
create table TARG_ALIAS (NAME varchar(255) not null, LabBookEntryID int8 not null, TARGETID int8 not null, primary key (LabBookEntryID));
create table TARG_MILESTONE (DATE_ TIMESTAMPTZ not null, LabBookEntryID int8 not null, EXPERIMENTID int8, STATUSID int8 not null, TARGETID int8, primary key (LabBookEntryID));
create table TARG_PROJECT (COMPLETENAME TEXT not null, SHORTNAME varchar(80) not null, STARTDATE TIMESTAMPTZ, LabBookEntryID int8 not null, PROJECTID int8, primary key (LabBookEntryID));
create table TARG_RESEARCHOBJECTIVE (BIOCHEMICALFUNCTION varchar(254), BIOLOGICALPROCESS varchar(254), CATALYTICACTIVITY varchar(254), CELLLOCATION varchar(80), CLIENTCOSTCODE TEXT, COMMONNAME varchar(80) not null unique, FUNCTIONDESCRIPTION TEXT, LOCALNAME varchar(80), PATHWAY varchar(254), SIMILARITYDETAILS TEXT, SYSTEMATICNAME varchar(80), WHYCHOSEN TEXT, LabBookEntryID int8 not null, OWNERID int8, primary key (LabBookEntryID));
create table TARG_SIMILARITYHIT (DESCRIPTION TEXT, EVALUE FLOAT8, SIMILARITYPERCENTAGE FLOAT8, LabBookEntryID int8 not null, ATTACHMENTID int8 not null, TARGETID int8 not null, primary key (LabBookEntryID));
create table TARG_TARGET (BIOCHEMICALFUNCTION varchar(254), BIOLOGICALPROCESS varchar(254), CATALYTICACTIVITY varchar(254), CELLLOCATION varchar(80), FUNCTIONDESCRIPTION TEXT, GENENAME varchar(80), NAME varchar(80) not null unique, ORF varchar(80), PATHWAY varchar(254), SIMILARITYDETAILS TEXT, TOPOLOGY varchar(254), WHYCHOSEN TEXT, LabBookEntryID int8 not null, PROTEINID int8 not null, SPECIESID int8, primary key (LabBookEntryID));
create table TARG_TARGET2NUCLAC (NUCTARGETID int8 not null, NUCLEICACIDID int8 not null, primary key (NUCTARGETID, NUCLEICACIDID));
create table TARG_TARGET2PROJECTS (TARGETID int8 not null, PROJECTID int8 not null, primary key (TARGETID, PROJECTID));
create table TARG_TARGETGROUP (GROUPINGTYPE varchar(80), NAME varchar(80) not null unique, LabBookEntryID int8 not null, TARGETGROUPID int8, primary key (LabBookEntryID));
create table TARG_TARGGR2TARGETS (TARGETGROUPID int8 not null, TARGETID int8 not null, primary key (TARGETGROUPID, TARGETID));
create table TRAG_RESEARCHOBJECTIVEELEMENT (ALWAYSINCLUDED BOOLEAN, APPROXBEGINSEQID INTEGER, APPROXENDSEQID INTEGER, COMPONENTTYPE varchar(32) not null, DOMAIN varchar(80), STATUS varchar(80), WHYCHOSEN TEXT, LabBookEntryID int8 not null, MOLECULEID int8, RESEARCHOBJECTIVEID int8 not null, TARGETID int8, primary key (LabBookEntryID));
create table cryz_cypade_possva (PARAMETERDEFINITIONID int8 not null, POSSIBLEVALUE varchar(255), ORDER_ int4 not null, primary key (PARAMETERDEFINITIONID, ORDER_));
create table expe_instrument2insttype (INSTRUMENTID int8 not null, INSTRUMENTTYPEID int8 not null, primary key (INSTRUMENTID, INSTRUMENTTYPEID));
create table hold_holdca2abstholders (ABSTHOLDERID int8 not null, HOLDERCATEGORYID int8 not null, primary key (ABSTHOLDERID, HOLDERCATEGORYID));
create table hold_holdca2absthoty (HOLDERCATEGORYID int8 not null, ABSTRACTHOLDERTYPEID int8 not null, primary key (HOLDERCATEGORYID, ABSTRACTHOLDERTYPEID));
create table sam_sampca2abstsa (ABSTRACTSAMPLEID int8 not null, SAMPLECATEGORYID int8 not null, primary key (ABSTRACTSAMPLEID, SAMPLECATEGORYID));
create table sam_sampca2user (USERID int8 not null, SAMPLECATEGORYID int8 not null, primary key (USERID, SAMPLECATEGORYID));
create index acco_permission_usergroup_inx on ACCO_PERMISSION (USERGROUPID);
create index acco_permission_ao_inx on ACCO_PERMISSION (ACCESSOBJECTID);
alter table ACCO_PERMISSION add constraint FKF8CC82A0B82FAF5E foreign key (ACCESSOBJECTID) references CORE_ACCESSOBJECT;
alter table ACCO_PERMISSION add constraint FKF8CC82A0385506E5 foreign key (SYSTEMCLASSID) references CORE_SYSTEMCLASS;
alter table ACCO_PERMISSION add constraint FKF8CC82A0C72F3607 foreign key (USERGROUPID) references ACCO_USERGROUP;
create index acco_pref_user_inx on ACCO_PREFERENCE (USERID);
alter table ACCO_PREFERENCE add constraint FKC0A379AC385506E5 foreign key (SYSTEMCLASSID) references CORE_SYSTEMCLASS;
alter table ACCO_PREFERENCE add constraint FKC0A379ACB81148D foreign key (USERID) references ACCO_USER;
create index acco_user_supervisor_inx on ACCO_USER (SUPERVISORID);
create index acco_user_person_inx on ACCO_USER (PERSONID);
alter table ACCO_USER add constraint FK39C1E55CB5AC617D foreign key (PERSONID) references PEOP_PERSON;
alter table ACCO_USER add constraint FK39C1E55C385506E5 foreign key (SYSTEMCLASSID) references CORE_SYSTEMCLASS;
alter table ACCO_USER add constraint FK39C1E55C7BE508EA foreign key (SUPERVISORID) references ACCO_USER;
create index acco_usergroup_header_inx on ACCO_USERGROUP (HEADERID);
alter table ACCO_USERGROUP add constraint FK1DB21283385506E5 foreign key (SYSTEMCLASSID) references CORE_SYSTEMCLASS;
alter table ACCO_USERGROUP add constraint FK1DB21283FADC62CF foreign key (HEADERID) references ACCO_USER;
alter table ACCO_USERGROUP2USER add constraint FK3B3C825A6033C3A7 foreign key (MEMBERUSERID) references ACCO_USER;
alter table ACCO_USERGROUP2USER add constraint FK3B3C825AC72F3607 foreign key (USERGROUPID) references ACCO_USERGROUP;
alter table CORE_ACCESSOBJECT add constraint FK15020243385506E5 foreign key (SYSTEMCLASSID) references CORE_SYSTEMCLASS;
alter table CORE_ANNOTATION add constraint FKB1CFDBCF66AD0C9 foreign key (ATTACHMENTID) references CORE_ATTACHMENT;
alter table CORE_APPLICATIONDATA add constraint FK78DB483A66AD0C9 foreign key (ATTACHMENTID) references CORE_ATTACHMENT;
create index core_attachment_pe_inx on CORE_ATTACHMENT (PARENTENTRYID);
create index core_attachment_author_inx on CORE_ATTACHMENT (AUTHORID);
alter table CORE_ATTACHMENT add constraint FK997749C3C4219D47 foreign key (PARENTENTRYID) references CORE_LABBOOKENTRY;
alter table CORE_ATTACHMENT add constraint FK997749C392C0DA4D foreign key (AUTHORID) references ACCO_USER;
alter table CORE_BOOKCITATION add constraint FK7DE59170F6883D51 foreign key (CITATIONID) references CORE_CITATION;
alter table CORE_BOOKMARK add constraint FKBC41D645A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table CORE_CITATION add constraint FK3336A78766AD0C9 foreign key (ATTACHMENTID) references CORE_ATTACHMENT;
alter table CORE_CONFERENCECITATION add constraint FKD0C3B4A3F6883D51 foreign key (CITATIONID) references CORE_CITATION;
create index core_externaldblink_dbname_inx on CORE_EXTERNALDBLINK (DBNAMEID);
alter table CORE_EXTERNALDBLINK add constraint FKF63805A3E99F3CC9 foreign key (DBNAMEID) references REF_DBNAME;
alter table CORE_EXTERNALDBLINK add constraint FKF63805A366AD0C9 foreign key (ATTACHMENTID) references CORE_ATTACHMENT;
alter table CORE_JOURNALCITATION add constraint FK17270E5EF6883D51 foreign key (CITATIONID) references CORE_CITATION;
create index core_labbookentry_le_inx on CORE_LABBOOKENTRY (LASTEDITORID);
create index core_labbookentry_creator_inx on CORE_LABBOOKENTRY (CREATORID);
create index core_labbookentry_access_inx on CORE_LABBOOKENTRY (ACCESSID);
alter table CORE_LABBOOKENTRY add constraint FK14FF48DC610514AE foreign key (CREATORID) references ACCO_USER;
alter table CORE_LABBOOKENTRY add constraint FK14FF48DC517CBADF foreign key (ACCESSID) references CORE_ACCESSOBJECT;
alter table CORE_LABBOOKENTRY add constraint FK14FF48DC32790645 foreign key (LASTEDITORID) references ACCO_USER;
alter table CORE_NOTE add constraint FK4942A49266AD0C9 foreign key (ATTACHMENTID) references CORE_ATTACHMENT;
alter table CORE_NOTE2RELATEDENTRYS add constraint FKBB2A4C2C1488C4A7 foreign key (NOTEID) references CORE_NOTE;
alter table CORE_NOTE2RELATEDENTRYS add constraint FKBB2A4C2C45A40A7B foreign key (LABBOOKENTRYID) references CORE_LABBOOKENTRY;
alter table CORE_THESISCITATION add constraint FK96337253F6883D51 foreign key (CITATIONID) references CORE_CITATION;
create index cryz_dropannotation_image_inx on CRYZ_DROPANNOTATION (IMAGEID);
create index cryz_dropannotation_score_inx on CRYZ_DROPANNOTATION (SCOREID);
create index cryz_dropannotation_sample_inx on CRYZ_DROPANNOTATION (SAMPLEID);
create index cryz_dropannotation_s_inx on CRYZ_DROPANNOTATION (SOFTWAREID);
create index cryz_dropannotation_holder_inx on CRYZ_DROPANNOTATION (HOLDERID);
alter table CRYZ_DROPANNOTATION add constraint FK8779FFAD98DFED6C foreign key (SAMPLEID) references SAM_SAMPLE;
alter table CRYZ_DROPANNOTATION add constraint FK8779FFADF92D0173 foreign key (SOFTWAREID) references EXPE_SOFTWARE;
alter table CRYZ_DROPANNOTATION add constraint FK8779FFAD2A5694F8 foreign key (SCOREID) references CRYZ_SCORE;
alter table CRYZ_DROPANNOTATION add constraint FK8779FFAD2915DC4A foreign key (IMAGEID) references CRYZ_IMAGE;
alter table CRYZ_DROPANNOTATION add constraint FK8779FFAD45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table CRYZ_DROPANNOTATION add constraint FK8779FFAD4EB8A6AE foreign key (HOLDERID) references HOLD_HOLDER;
create index cryz_image_instrument_inx on CRYZ_IMAGE (INSTRUMENTID);
create index cryz_image_scheduletask_inx on CRYZ_IMAGE (SCHEDULEDTASKID);
create index cryz_image_wellimagetype_inx on CRYZ_IMAGE (WELLIMAGETYPEID);
create index cryz_image_sample_inx on CRYZ_IMAGE (SAMPLEID);
create index cryz_image_imagetype_inx on CRYZ_IMAGE (IMAGETYPEID);
alter table CRYZ_IMAGE add constraint FKC9A2AC0C98DFED6C foreign key (SAMPLEID) references SAM_SAMPLE;
alter table CRYZ_IMAGE add constraint FKC9A2AC0CD024DEFB foreign key (IMAGETYPEID) references REF_IMAGETYPE;
alter table CRYZ_IMAGE add constraint FKC9A2AC0C8EBD226F foreign key (SCHEDULEDTASKID) references SCHE_SCHEDULEDTASK;
alter table CRYZ_IMAGE add constraint FKC9A2AC0C19C4EB73 foreign key (INSTRUMENTID) references EXPE_INSTRUMENT;
alter table CRYZ_IMAGE add constraint FKC9A2AC0CCC914DA2 foreign key (WELLIMAGETYPEID) references CRYZ_WELLIMAGETYPE;
alter table CRYZ_IMAGE add constraint FKC9A2AC0C45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index cryz_parameter_pd_inx on CRYZ_PARAMETER (PARAMETERDEFINITIONID);
create index cryz_parameter_image_inx on CRYZ_PARAMETER (IMAGEID);
alter table CRYZ_PARAMETER add constraint FK4A04EDDA578D9E96 foreign key (PARAMETERDEFINITIONID) references CRYZ_PARAMETERDEFINITION;
alter table CRYZ_PARAMETER add constraint FK4A04EDDA2915DC4A foreign key (IMAGEID) references CRYZ_IMAGE;
alter table CRYZ_PARAMETER add constraint FK4A04EDDA45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table CRYZ_PARAMETERDEFINITION add constraint FKF9B406AD45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index cryz_score_scoringscheme_inx on CRYZ_SCORE (SCORINGSCHEMEID);
alter table CRYZ_SCORE add constraint FKCA2B414345A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table CRYZ_SCORE add constraint FKCA2B414322C2D4DC foreign key (SCORINGSCHEMEID) references CRYZ_SCORINGSCHEME;
alter table CRYZ_SCORINGSCHEME add constraint FKD23F4EE545A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table CRYZ_WELLIMAGETYPE add constraint FK69A92BB845A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index expe_experiment_ro_inx on EXPE_EXPERIMENT (RESEARCHOBJECTIVEID);
create index expe_experiment_protocol_inx on EXPE_EXPERIMENT (PROTOCOLID);
create index expe_experiment_instrument_inx on EXPE_EXPERIMENT (INSTRUMENTID);
create index expe_experiment_group_inx on EXPE_EXPERIMENT (GROUPID);
create index expe_experiment_method_inx on EXPE_EXPERIMENT (METHODID);
create index expe_experiment_operator_inx on EXPE_EXPERIMENT (OPERATORID);
create index expe_experiment_et_inx on EXPE_EXPERIMENT (EXPERIMENTTYPEID);
create index expe_experiment_eg_inx on EXPE_EXPERIMENT (EXPERIMENTGROUPID);
alter table EXPE_EXPERIMENT add constraint FKD0E6AAB49B03E5D3 foreign key (EXPERIMENTTYPEID) references REF_EXPERIMENTTYPE;
alter table EXPE_EXPERIMENT add constraint FKD0E6AAB46F99111A foreign key (PROTOCOLID) references PROT_PROTOCOL;
alter table EXPE_EXPERIMENT add constraint FKD0E6AAB41F3823E7 foreign key (METHODID) references EXPE_METHOD;
alter table EXPE_EXPERIMENT add constraint FKD0E6AAB419C4EB73 foreign key (INSTRUMENTID) references EXPE_INSTRUMENT;
alter table EXPE_EXPERIMENT add constraint FKD0E6AAB4CBB3F861 foreign key (GROUPID) references PEOP_GROUP;
alter table EXPE_EXPERIMENT add constraint FKD0E6AAB4805B47B5 foreign key (EXPERIMENTGROUPID) references EXPE_EXPERIMENTGROUP;
alter table EXPE_EXPERIMENT add constraint FKD0E6AAB4E71EA01 foreign key (RESEARCHOBJECTIVEID) references TARG_RESEARCHOBJECTIVE;
alter table EXPE_EXPERIMENT add constraint FKD0E6AAB43D987F26 foreign key (OPERATORID) references ACCO_USER;
alter table EXPE_EXPERIMENT add constraint FKD0E6AAB445A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table EXPE_EXPERIMENTGROUP add constraint FK1DEAE42B45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index expe_inputsample_sample_inx on EXPE_INPUTSAMPLE (SAMPLEID);
create index expe_inputsample_e_inx on EXPE_INPUTSAMPLE (EXPERIMENTID);
create index expe_inputsample_ris_inx on EXPE_INPUTSAMPLE (REFINPUTSAMPLEID);
alter table EXPE_INPUTSAMPLE add constraint FKCED55FD98DFED6C foreign key (SAMPLEID) references SAM_SAMPLE;
alter table EXPE_INPUTSAMPLE add constraint FKCED55FDF53AF16C foreign key (REFINPUTSAMPLEID) references PROT_REFINPUTSAMPLE;
alter table EXPE_INPUTSAMPLE add constraint FKCED55FD6C002E1F foreign key (EXPERIMENTID) references EXPE_EXPERIMENT;
alter table EXPE_INPUTSAMPLE add constraint FKCED55FD45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index expe_instrument_m_inx on EXPE_INSTRUMENT (MANUFACTURERID);
create index expe_instrument_dwit_inx on EXPE_INSTRUMENT (DEFAULTWELLIMAGETYPEID);
create index expe_instrument_dit_inx on EXPE_INSTRUMENT (DEFAULTIMAGETYPEID);
create index expe_instrument_location_inx on EXPE_INSTRUMENT (LOCATIONID);
alter table EXPE_INSTRUMENT add constraint FK292A329EA9533F97 foreign key (LOCATIONID) references LOCA_LOCATION;
alter table EXPE_INSTRUMENT add constraint FK292A329EAE8A461A foreign key (DEFAULTIMAGETYPEID) references REF_IMAGETYPE;
alter table EXPE_INSTRUMENT add constraint FK292A329E571067E foreign key (MANUFACTURERID) references PEOP_ORGANISATION;
alter table EXPE_INSTRUMENT add constraint FK292A329E9DA00D41 foreign key (DEFAULTWELLIMAGETYPEID) references CRYZ_WELLIMAGETYPE;
alter table EXPE_INSTRUMENT add constraint FK292A329E45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index expe_method_software_inx on EXPE_METHOD (SOFTWAREID);
create index expe_method_instrument_inx on EXPE_METHOD (INSTRUMENTID);
alter table EXPE_METHOD add constraint FK98BF9B18F92D0173 foreign key (SOFTWAREID) references EXPE_SOFTWARE;
alter table EXPE_METHOD add constraint FK98BF9B1819C4EB73 foreign key (INSTRUMENTID) references EXPE_INSTRUMENT;
alter table EXPE_METHOD add constraint FK98BF9B1845A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index expe_methpa_method_inx on EXPE_METHODPARAMETER (METHODID);
alter table EXPE_METHODPARAMETER add constraint FK471823711F3823E7 foreign key (METHODID) references EXPE_METHOD;
alter table EXPE_METHODPARAMETER add constraint FK4718237145A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index expe_outputsample_ros_inx on EXPE_OUTPUTSAMPLE (REFOUTPUTSAMPLEID);
create index expe_outputsample_e_inx on EXPE_OUTPUTSAMPLE (EXPERIMENTID);
alter table EXPE_OUTPUTSAMPLE add constraint FK77CC02E298DFED6C foreign key (SAMPLEID) references SAM_SAMPLE;
alter table EXPE_OUTPUTSAMPLE add constraint FK77CC02E25D2A5E28 foreign key (REFOUTPUTSAMPLEID) references PROT_REFOUTPUTSAMPLE;
alter table EXPE_OUTPUTSAMPLE add constraint FK77CC02E26C002E1F foreign key (EXPERIMENTID) references EXPE_EXPERIMENT;
alter table EXPE_OUTPUTSAMPLE add constraint FK77CC02E245A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index expe_parameter_pd_inx on EXPE_PARAMETER (PARAMETERDEFINITIONID);
create index expe_parameter_experiment_inx on EXPE_PARAMETER (EXPERIMENTID);
alter table EXPE_PARAMETER add constraint FK28D12DF259EEC984 foreign key (PARAMETERDEFINITIONID) references PROT_PARAMETERDEFINITION;
alter table EXPE_PARAMETER add constraint FK28D12DF26C002E1F foreign key (EXPERIMENTID) references EXPE_EXPERIMENT;
alter table EXPE_PARAMETER add constraint FK28D12DF245A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table EXPE_SOFTWARE add constraint FKD053761E45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table EXPE_SOFTWARE_TASKS add constraint FKFF38CE0DF92D0173 foreign key (SOFTWAREID) references EXPE_SOFTWARE;
alter table EXPE_WORKFLOW add constraint FK83CBEC3645A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table EXPE_WORKFLOW2PROTOCOLS add constraint FKF7CA0D7F6F99111A foreign key (PROTOCOLID) references PROT_PROTOCOL;
alter table EXPE_WORKFLOW2PROTOCOLS add constraint FKF7CA0D7FEA8DF5A8 foreign key (WORKFLOWID) references EXPE_WORKFLOW;
alter table EXPE_WORKFLOW2RESEARCHOBJECTIVE add constraint FKC5396AA2C8A7C45C foreign key (PROJECTID) references TARG_RESEARCHOBJECTIVE;
alter table EXPE_WORKFLOW2RESEARCHOBJECTIVE add constraint FKC5396AA2EA8DF5A8 foreign key (WORKFLOWID) references EXPE_WORKFLOW;
create index hold_abstractholder_p_inx on HOLD_ABSTRACTHOLDER (ABSTRACTHOLDERID);
create index hold_abstractholder_ht_inx on HOLD_ABSTRACTHOLDER (HOLDERTYPEID);
alter table HOLD_ABSTRACTHOLDER add constraint FKD6FF0BCE4E441F33 foreign key (HOLDERTYPEID) references REF_ABSTRACTHOLDERTYPE;
alter table HOLD_ABSTRACTHOLDER add constraint FKD6FF0BCE45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table HOLD_ABSTRACTHOLDER add constraint FKD6FF0BCEF334A492 foreign key (ABSTRACTHOLDERID) references HOLD_ABSTRACTHOLDER;
create index hold_holder_startdate_inx on HOLD_HOLDER (STARTDATE);
create index hold_holder_lasttask_inx on HOLD_HOLDER (LASTTASKID);
create index hold_holder_firstsample_inx on HOLD_HOLDER (FIRSTSAMPLEID);
alter table HOLD_HOLDER add constraint FKFFE6CD2CC7EF2198 foreign key (LASTTASKID) references SCHE_SCHEDULEDTASK;
alter table HOLD_HOLDER add constraint FKFFE6CD2CF334A492 foreign key (ABSTRACTHOLDERID) references HOLD_ABSTRACTHOLDER;
alter table HOLD_HOLDER add constraint FKFFE6CD2C2C9101C foreign key (FIRSTSAMPLEID) references SAM_SAMPLE;
create index hold_holderlocation_l_inx on HOLD_HOLDERLOCATION (LOCATIONID);
create index hold_holderlocation_holder_inx on HOLD_HOLDERLOCATION (HOLDERID);
alter table HOLD_HOLDERLOCATION add constraint FKA28270E1A9533F97 foreign key (LOCATIONID) references LOCA_LOCATION;
alter table HOLD_HOLDERLOCATION add constraint FKA28270E145A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table HOLD_HOLDERLOCATION add constraint FKA28270E14EB8A6AE foreign key (HOLDERID) references HOLD_HOLDER;
create index hold_htp_holdertype_inx on HOLD_HOLDERTYPEPOSITION (HOLDERTYPEID);
alter table HOLD_HOLDERTYPEPOSITION add constraint FK340AA18FB4E81F71 foreign key (HOLDERTYPEID) references REF_HOLDERTYPE;
alter table HOLD_HOLDERTYPEPOSITION add constraint FK340AA18F45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table HOLD_REFHOLDER add constraint FK1177E05FF334A492 foreign key (ABSTRACTHOLDERID) references HOLD_ABSTRACTHOLDER;
create index hold_rho_holder_inx on HOLD_REFHOLDEROFFSET (HOLDERID);
create index hold_rho_refholder_inx on HOLD_REFHOLDEROFFSET (REFHOLDERID);
alter table HOLD_REFHOLDEROFFSET add constraint FK7C4A35B2A3C3865E foreign key (REFHOLDERID) references HOLD_REFHOLDER;
alter table HOLD_REFHOLDEROFFSET add constraint FK7C4A35B245A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table HOLD_REFHOLDEROFFSET add constraint FK7C4A35B24EB8A6AE foreign key (HOLDERID) references HOLD_HOLDER;
alter table HOLD_REFHOLDERSOURCE add constraint FK83A3393AA3C3865E foreign key (REFHOLDERID) references HOLD_REFHOLDER;
alter table HOLD_REFHOLDERSOURCE add constraint FK83A3393A7F9149B9 foreign key (SUPPLIERID) references PEOP_ORGANISATION;
alter table HOLD_REFHOLDERSOURCE add constraint FK83A3393A45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index hold_rsp_refsample_inx on HOLD_REFSAMPLEPOSITION (REFSAMPLEID);
create index hold_rsp_refholder_inx on HOLD_REFSAMPLEPOSITION (RefHOLDERID);
alter table HOLD_REFSAMPLEPOSITION add constraint FKBE856486A3C3865E foreign key (RefHOLDERID) references HOLD_REFHOLDER;
alter table HOLD_REFSAMPLEPOSITION add constraint FKBE85648645A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table HOLD_REFSAMPLEPOSITION add constraint FKBE856486C7C01158 foreign key (REFSAMPLEID) references SAM_REFSAMPLE;
create index loca_location_location_inx on LOCA_LOCATION (LOCATIONID);
create index loca_location_organisation_inx on LOCA_LOCATION (ORGANISATIONID);
alter table LOCA_LOCATION add constraint FKD2933913A9533F97 foreign key (LOCATIONID) references LOCA_LOCATION;
alter table LOCA_LOCATION add constraint FKD29339139B62C547 foreign key (ORGANISATIONID) references PEOP_ORGANISATION;
alter table LOCA_LOCATION add constraint FKD293391345A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table MOLE_ABSTCO_KEYWORDS add constraint FK85E2B8F7737B3265 foreign key (ABSTRACTCOMPONENTID) references MOLE_ABSTRACTCOMPONENT;
alter table MOLE_ABSTCO_SYNONYMS add constraint FKD3B25D25737B3265 foreign key (ABSTRACTCOMPONENTID) references MOLE_ABSTRACTCOMPONENT;
create index mole_abstractcomponent_ns_inx on MOLE_ABSTRACTCOMPONENT (NATURALSOURCEID);
alter table MOLE_ABSTRACTCOMPONENT add constraint FK2CDC1E5745A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table MOLE_ABSTRACTCOMPONENT add constraint FK2CDC1E57D3971EDB foreign key (NATURALSOURCEID) references REF_ORGANISM;
alter table MOLE_COMPCA2COMPONENTS add constraint FK4A9D5E579CC3E68A foreign key (CATEGORYID) references REF_COMPONENTCATEGORY;
alter table MOLE_COMPCA2COMPONENTS add constraint FK4A9D5E5781C32BC7 foreign key (COMPONENTID) references MOLE_ABSTRACTCOMPONENT;
alter table MOLE_CONSTRUCT add constraint FK28BB5B13A4680548 foreign key (MOLECULEID) references MOLE_MOLECULE;
alter table MOLE_EXTENSION add constraint FK1D5C137BA4680548 foreign key (MOLECULEID) references MOLE_MOLECULE;
alter table MOLE_HOST add constraint FKD686DCCC5543837A foreign key (SUBSTANCEID) references MOLE_ABSTRACTCOMPONENT;
alter table MOLE_HOST2ORGANISATION add constraint FK63447CC0CEC6B38C foreign key (HOSTID) references MOLE_HOST;
alter table MOLE_HOST2ORGANISATION add constraint FK63447CC09B62C547 foreign key (ORGANISATIONID) references PEOP_ORGANISATION;
alter table MOLE_MOLECULE add constraint FK45B3E7AA5543837A foreign key (SUBSTANCEID) references MOLE_ABSTRACTCOMPONENT;
alter table MOLE_MOLECULE2RELAREOBEL add constraint FKC46D9B1D7F20B0DE foreign key (TRIALMOLECULEID) references MOLE_MOLECULE;
alter table MOLE_MOLECULE2RELAREOBEL add constraint FKC46D9B1D509911E3 foreign key (RELATEDROELEMENTID) references TRAG_RESEARCHOBJECTIVEELEMENT;
create index mole_mf_refmolecule_inx on MOLE_MOLECULEFEATURE (REFMOLECULEID);
create index mole_mf_molecule_inx on MOLE_MOLECULEFEATURE (MOLECULEID);
alter table MOLE_MOLECULEFEATURE add constraint FK96600BEC45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table MOLE_MOLECULEFEATURE add constraint FK96600BEC36F6621B foreign key (REFMOLECULEID) references MOLE_MOLECULE;
alter table MOLE_MOLECULEFEATURE add constraint FK96600BECA4680548 foreign key (MOLECULEID) references MOLE_MOLECULE;
alter table MOLE_PRIMER add constraint FK5E0F47F7A4680548 foreign key (MOLECULEID) references MOLE_MOLECULE;
create index peop_group_organisation_inx on PEOP_GROUP (ORGANISATIONID);
alter table PEOP_GROUP add constraint FK8A0003769B62C547 foreign key (ORGANISATIONID) references PEOP_ORGANISATION;
alter table PEOP_GROUP add constraint FK8A00037645A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table PEOP_ORGANISATION add constraint FK987C4BE345A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table PEOP_ORGA_ADDRESSES add constraint FK8636D8899B62C547 foreign key (ORGANISATIONID) references PEOP_ORGANISATION;
alter table PEOP_PERSINGR_PHONNU add constraint FKB5660FCED18A88AD foreign key (PERSONINGROUPID) references PEOP_PERSONINGROUP;
create index peop_person_currentgroup_inx on PEOP_PERSON (CURRENTGROUPID);
alter table PEOP_PERSON add constraint FKC4A62D1E9B7D0C8 foreign key (CURRENTGROUPID) references PEOP_GROUP;
alter table PEOP_PERSON add constraint FKC4A62D1E45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index peop_personingroup_group_inx on PEOP_PERSONINGROUP (GROUPID);
create index peop_personingroup_person_inx on PEOP_PERSONINGROUP (PERSONID);
alter table PEOP_PERSONINGROUP add constraint FK34B0597CB5AC617D foreign key (PERSONID) references PEOP_PERSON;
alter table PEOP_PERSONINGROUP add constraint FK34B0597CCBB3F861 foreign key (GROUPID) references PEOP_GROUP;
alter table PEOP_PERSONINGROUP add constraint FK34B0597C45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table PEOP_PERSON_MIDDIN add constraint FKBEDA3F82B5AC617D foreign key (PERSONID) references PEOP_PERSON;
alter table PROT_PARADE_POSSVA add constraint FKF2966E5059EEC984 foreign key (PARAMETERDEFINITIONID) references PROT_PARAMETERDEFINITION;
create index prot_pd_protocol_inx on PROT_PARAMETERDEFINITION (PROTOCOLID);
alter table PROT_PARAMETERDEFINITION add constraint FK38F93CC46F99111A foreign key (PROTOCOLID) references PROT_PROTOCOL;
alter table PROT_PARAMETERDEFINITION add constraint FK38F93CC445A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index prot_protocol_et_inx on PROT_PROTOCOL (EXPERIMENTTYPEID);
create index prot_protocol_it_inx on PROT_PROTOCOL (INSTRUMENTTYPEID);
alter table PROT_PROTOCOL add constraint FK139AF8709B03E5D3 foreign key (EXPERIMENTTYPEID) references REF_EXPERIMENTTYPE;
alter table PROT_PROTOCOL add constraint FK139AF87032C1D927 foreign key (INSTRUMENTTYPEID) references REF_INSTRUMENTTYPE;
alter table PROT_PROTOCOL add constraint FK139AF87045A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table PROT_PROTOCOL_REMARKS add constraint FKFB7C68046F99111A foreign key (PROTOCOLID) references PROT_PROTOCOL;
create index prot_ris_protocol_inx on PROT_REFINPUTSAMPLE (PROTOCOLID);
create index prot_ris_samplecategory_inx on PROT_REFINPUTSAMPLE (SAMPLECATEGORYID);
create index prot_ris_recipe_inx on PROT_REFINPUTSAMPLE (RECIPEID);
alter table PROT_REFINPUTSAMPLE add constraint FKDD4027596F99111A foreign key (PROTOCOLID) references PROT_PROTOCOL;
alter table PROT_REFINPUTSAMPLE add constraint FKDD40275945A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table PROT_REFINPUTSAMPLE add constraint FKDD4027595FF112A9 foreign key (RECIPEID) references SAM_REFSAMPLE;
alter table PROT_REFINPUTSAMPLE add constraint FKDD402759B4E92575 foreign key (SAMPLECATEGORYID) references REF_SAMPLECATEGORY;
create index prot_ros_samplecategory_inx on PROT_REFOUTPUTSAMPLE (SAMPLECATEGORYID);
create index prot_ros_protocol_inx on PROT_REFOUTPUTSAMPLE (PROTOCOLID);
alter table PROT_REFOUTPUTSAMPLE add constraint FKB1D35D066F99111A foreign key (PROTOCOLID) references PROT_PROTOCOL;
alter table PROT_REFOUTPUTSAMPLE add constraint FKB1D35D0645A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table PROT_REFOUTPUTSAMPLE add constraint FKB1D35D06B4E92575 foreign key (SAMPLECATEGORYID) references REF_SAMPLECATEGORY;
alter table REF_ABSTRACTHOLDERTYPE add constraint FK12B307D4F8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_COMPONENTCATEGORY add constraint FK55CEBC0FF8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_CRYSTALTYPE add constraint FKFBC9A184B4E81F71 foreign key (HOLDERTYPEID) references REF_HOLDERTYPE;
alter table REF_DBNAME add constraint FKB6CA7555F8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_EXPERIMENTTYPE add constraint FKB37F6603F8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_HAZARDPHRASE add constraint FK1D43C997F8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_HOLDERCATEGORY add constraint FK387E5FF6F8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
create index ref_holdertype_dsp_inx on REF_HOLDERTYPE (DefaultSchedulePlanID);
alter table REF_HOLDERTYPE add constraint FKD1FD7632938CEC55 foreign key (ABSTRACTHOLDERTYPEID) references REF_ABSTRACTHOLDERTYPE;
alter table REF_HOLDERTYPE add constraint FKD1FD763248A415EC foreign key (DefaultSchedulePlanID) references SCHE_SCHEDULEPLAN;
create index ref_hts_holdertype_inx on REF_HOLDERTYPESOURCE (HOLDERTYPEID);
create index ref_hts_supplier_inx on REF_HOLDERTYPESOURCE (SUPPLIERID);
alter table REF_HOLDERTYPESOURCE add constraint FKA6A7E4CDF8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_HOLDERTYPESOURCE add constraint FKA6A7E4CD4E441F33 foreign key (HOLDERTYPEID) references REF_ABSTRACTHOLDERTYPE;
alter table REF_HOLDERTYPESOURCE add constraint FKA6A7E4CD7F9149B9 foreign key (SUPPLIERID) references PEOP_ORGANISATION;
alter table REF_IMAGETYPE add constraint FK4872A629F8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_INSTRUMENTTYPE add constraint FKAD88E8EDF8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_ORGANISM add constraint FKE721B71EF8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_PINTYPE add constraint FKA949BA63938CEC55 foreign key (ABSTRACTHOLDERTYPEID) references REF_ABSTRACTHOLDERTYPE;
alter table REF_SAMPLECATEGORY add constraint FKACE29F4F8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_TARGETSTATUS add constraint FK5E9B390FF8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
create index ref_workflowitem_et_inx on REF_WORKFLOWITEM (EXPERIMENTTYPEID);
create index ref_workflowitem_status_inx on REF_WORKFLOWITEM (STATUSID);
alter table REF_WORKFLOWITEM add constraint FKA54D839EF8F98163 foreign key (PublicEntryID) references REF_PUBLICENTRY;
alter table REF_WORKFLOWITEM add constraint FKA54D839E9B03E5D3 foreign key (EXPERIMENTTYPEID) references REF_EXPERIMENTTYPE;
alter table REF_WORKFLOWITEM add constraint FKA54D839EABBC44DA foreign key (STATUSID) references REF_TARGETSTATUS;
alter table SAM_ABSTRACTSAMPLE add constraint FK9A3000CC45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table SAM_ABSTSA2HAZAPH add constraint FK84A833FA6D03126F foreign key (OTHERROLE) references SAM_ABSTRACTSAMPLE;
alter table SAM_ABSTSA2HAZAPH add constraint FK84A833FABE6BB47B foreign key (HAZARDPHRASEID) references REF_HAZARDPHRASE;
alter table SAM_CRYSTALSAMPLE add constraint FK6C4167C098DFED6C foreign key (SAMPLEID) references SAM_SAMPLE;
alter table SAM_REFSAMPLE add constraint FK3E8C1B5D3E228950 foreign key (ABSTRACTSAMPLEID) references SAM_ABSTRACTSAMPLE;
alter table SAM_REFSAMPLESOURCE add constraint FK3792BDB87F9149B9 foreign key (SUPPLIERID) references PEOP_ORGANISATION;
alter table SAM_REFSAMPLESOURCE add constraint FK3792BDB845A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table SAM_REFSAMPLESOURCE add constraint FK3792BDB8C7C01158 foreign key (REFSAMPLEID) references SAM_REFSAMPLE;
create index sam_sample_refsample_inx on SAM_SAMPLE (REFSAMPLEID);
create index sam_sample_holder_inx on SAM_SAMPLE (HOLDERID);
create index sam_sample_assignto_inx on SAM_SAMPLE (ASSIGNTOID);
alter table SAM_SAMPLE add constraint FK4AB4C22A3E228950 foreign key (ABSTRACTSAMPLEID) references SAM_ABSTRACTSAMPLE;
alter table SAM_SAMPLE add constraint FK4AB4C22A7A84BCAC foreign key (ASSIGNTOID) references ACCO_USER;
alter table SAM_SAMPLE add constraint FK4AB4C22A4EB8A6AE foreign key (HOLDERID) references HOLD_HOLDER;
alter table SAM_SAMPLE add constraint FK4AB4C22AC7C01158 foreign key (REFSAMPLEID) references SAM_REFSAMPLE;
create index sam_samplecomponent_rc_inx on SAM_SAMPLECOMPONENT (REFCOMPONENTID);
create index sam_samplecomponent_c_inx on SAM_SAMPLECOMPONENT (CONTAINERID);
create index sam_samplecomponent_as_inx on SAM_SAMPLECOMPONENT (ABSTRACTSAMPLEID);
create index sam_samplecomponent_roe_inx on SAM_SAMPLECOMPONENT (RESEARCHOBJECTIVELEMENTID);
alter table SAM_SAMPLECOMPONENT add constraint FK8E3939F341006954 foreign key (REFCOMPONENTID) references MOLE_ABSTRACTCOMPONENT;
alter table SAM_SAMPLECOMPONENT add constraint FK8E3939F3403528F2 foreign key (CONTAINERID) references SAM_SAMPLECOMPONENT;
alter table SAM_SAMPLECOMPONENT add constraint FK8E3939F33E228950 foreign key (ABSTRACTSAMPLEID) references SAM_ABSTRACTSAMPLE;
alter table SAM_SAMPLECOMPONENT add constraint FK8E3939F345A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table SAM_SAMPLECOMPONENT add constraint FK8E3939F31CAEAD24 foreign key (RESEARCHOBJECTIVELEMENTID) references TRAG_RESEARCHOBJECTIVEELEMENT;
create index sche_scheduledtask_spo_inx on SCHE_SCHEDULEDTASK (SchedulePlanOffsetID);
create index sche_scheduledtask_h_inx on SCHE_SCHEDULEDTASK (HOLDERID);
create index sche_scheduledtask_i_inx on SCHE_SCHEDULEDTASK (INSTRUMENTID);
alter table SCHE_SCHEDULEDTASK add constraint FK703F36205A5E25F1 foreign key (SchedulePlanOffsetID) references SCHE_SCHEDULEPLANOFFSET;
alter table SCHE_SCHEDULEDTASK add constraint FK703F362019C4EB73 foreign key (INSTRUMENTID) references EXPE_INSTRUMENT;
alter table SCHE_SCHEDULEDTASK add constraint FK703F362045A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table SCHE_SCHEDULEDTASK add constraint FK703F36204EB8A6AE foreign key (HOLDERID) references HOLD_HOLDER;
alter table SCHE_SCHEDULEPLAN add constraint FKA8CD91F245A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index sche_spo_scheduleplan_inx on SCHE_SCHEDULEPLANOFFSET (SchedulePlanID);
alter table SCHE_SCHEDULEPLANOFFSET add constraint FKF0B2D05CE48C56B foreign key (SchedulePlanID) references SCHE_SCHEDULEPLAN;
alter table SCHE_SCHEDULEPLANOFFSET add constraint FKF0B2D0545A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index targ_alias_target_inx on TARG_ALIAS (TARGETID);
alter table TARG_ALIAS add constraint FK65481D135336A9B3 foreign key (TARGETID) references TARG_TARGET;
alter table TARG_ALIAS add constraint FK65481D1345A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index targ_milestone_target_inx on TARG_MILESTONE (TARGETID);
create index targ_milestone_experiment_inx on TARG_MILESTONE (EXPERIMENTID);
create index targ_milestone_status_inx on TARG_MILESTONE (STATUSID);
alter table TARG_MILESTONE add constraint FK7C3C7EB35336A9B3 foreign key (TARGETID) references TARG_TARGET;
alter table TARG_MILESTONE add constraint FK7C3C7EB3ABBC44DA foreign key (STATUSID) references REF_TARGETSTATUS;
alter table TARG_MILESTONE add constraint FK7C3C7EB36C002E1F foreign key (EXPERIMENTID) references EXPE_EXPERIMENT;
alter table TARG_MILESTONE add constraint FK7C3C7EB345A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index targ_project_project_inx on TARG_PROJECT (PROJECTID);
alter table TARG_PROJECT add constraint FK57C8291C58259E17 foreign key (PROJECTID) references TARG_PROJECT;
alter table TARG_PROJECT add constraint FK57C8291C45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index targ_ro_owner_inx on TARG_RESEARCHOBJECTIVE (OWNERID);
alter table TARG_RESEARCHOBJECTIVE add constraint FK2A93F84145A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table TARG_RESEARCHOBJECTIVE add constraint FK2A93F841FE780175 foreign key (OWNERID) references ACCO_USER;
create index targ_similarityhit_edbl_inx on TARG_SIMILARITYHIT (ATTACHMENTID);
create index targ_similarityhit_target_inx on TARG_SIMILARITYHIT (TARGETID);
alter table TARG_SIMILARITYHIT add constraint FKC85691935336A9B3 foreign key (TARGETID) references TARG_TARGET;
alter table TARG_SIMILARITYHIT add constraint FKC85691935FD6F0E9 foreign key (ATTACHMENTID) references CORE_EXTERNALDBLINK;
alter table TARG_SIMILARITYHIT add constraint FKC856919345A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
create index targ_target_species_inx on TARG_TARGET (SPECIESID);
create index targ_target_protein_inx on TARG_TARGET (PROTEINID);
alter table TARG_TARGET add constraint FK6390C30ED3135493 foreign key (SPECIESID) references REF_ORGANISM;
alter table TARG_TARGET add constraint FK6390C30E45A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table TARG_TARGET add constraint FK6390C30ED1CC5705 foreign key (PROTEINID) references MOLE_MOLECULE;
alter table TARG_TARGET2NUCLAC add constraint FK8CCD4C76D488084E foreign key (NUCLEICACIDID) references MOLE_MOLECULE;
alter table TARG_TARGET2NUCLAC add constraint FK8CCD4C764983192F foreign key (NUCTARGETID) references TARG_TARGET;
alter table TARG_TARGET2PROJECTS add constraint FKD41B835E5336A9B3 foreign key (TARGETID) references TARG_TARGET;
alter table TARG_TARGET2PROJECTS add constraint FKD41B835E58259E17 foreign key (PROJECTID) references TARG_PROJECT;
create index targ_targetgroup_tg_inx on TARG_TARGETGROUP (TARGETGROUPID);
alter table TARG_TARGETGROUP add constraint FK3363F41145A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table TARG_TARGETGROUP add constraint FK3363F4118B86E8A1 foreign key (TARGETGROUPID) references TARG_TARGETGROUP;
alter table TARG_TARGGR2TARGETS add constraint FKE8FBE9BA5336A9B3 foreign key (TARGETID) references TARG_TARGET;
alter table TARG_TARGGR2TARGETS add constraint FKE8FBE9BA8B86E8A1 foreign key (TARGETGROUPID) references TARG_TARGETGROUP;
create index targ_roe_target_inx on TRAG_RESEARCHOBJECTIVEELEMENT (TARGETID);
create index targ_roe_researchobjective_inx on TRAG_RESEARCHOBJECTIVEELEMENT (RESEARCHOBJECTIVEID);
create index targ_roe_molecule_inx on TRAG_RESEARCHOBJECTIVEELEMENT (MOLECULEID);
alter table TRAG_RESEARCHOBJECTIVEELEMENT add constraint FKD4DF77F95336A9B3 foreign key (TARGETID) references TARG_TARGET;
alter table TRAG_RESEARCHOBJECTIVEELEMENT add constraint FKD4DF77F9E71EA01 foreign key (RESEARCHOBJECTIVEID) references TARG_RESEARCHOBJECTIVE;
alter table TRAG_RESEARCHOBJECTIVEELEMENT add constraint FKD4DF77F945A40A7B foreign key (LabBookEntryID) references CORE_LABBOOKENTRY;
alter table TRAG_RESEARCHOBJECTIVEELEMENT add constraint FKD4DF77F9A4680548 foreign key (MOLECULEID) references MOLE_MOLECULE;
alter table cryz_cypade_possva add constraint FK12D769D2578D9E96 foreign key (PARAMETERDEFINITIONID) references CRYZ_PARAMETERDEFINITION;
alter table expe_instrument2insttype add constraint FKD6BA63D419C4EB73 foreign key (INSTRUMENTID) references EXPE_INSTRUMENT;
alter table expe_instrument2insttype add constraint FKD6BA63D432C1D927 foreign key (INSTRUMENTTYPEID) references REF_INSTRUMENTTYPE;
alter table hold_holdca2abstholders add constraint FKC400DDB0651418F9 foreign key (HOLDERCATEGORYID) references REF_HOLDERCATEGORY;
alter table hold_holdca2abstholders add constraint FKC400DDB0E1A02AB2 foreign key (ABSTHOLDERID) references HOLD_ABSTRACTHOLDER;
alter table hold_holdca2absthoty add constraint FKFD882103938CEC55 foreign key (ABSTRACTHOLDERTYPEID) references REF_ABSTRACTHOLDERTYPE;
alter table hold_holdca2absthoty add constraint FKFD882103651418F9 foreign key (HOLDERCATEGORYID) references REF_HOLDERCATEGORY;
alter table sam_sampca2abstsa add constraint FKCFDCA6F33E228950 foreign key (ABSTRACTSAMPLEID) references SAM_ABSTRACTSAMPLE;
alter table sam_sampca2abstsa add constraint FKCFDCA6F3B4E92575 foreign key (SAMPLECATEGORYID) references REF_SAMPLECATEGORY;
alter table sam_sampca2user add constraint FK7F0DD36EB81148D foreign key (USERID) references ACCO_USER;
alter table sam_sampca2user add constraint FK7F0DD36EB4E92575 foreign key (SAMPLECATEGORYID) references REF_SAMPLECATEGORY;
