//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OPPF.XML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/xsd/RI/ImageInfo.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.oppf.ox.ac.uk/xsd/RI/ImageInfo.xsd", IsNullable=false)]
    public partial class ImageInfo {
        
        private string urlField;
        
        private string imagerField;
        
        private string imagingIdField;
        
        private string plateIdField;
        
        private string dropField;
        
        private ImageInfoImageType imageTypeField;
        
        private System.DateTime imagedAtField;
        
        private double zoomField;
        
        private Size sizeInPixelsField;
        
        private DoubleSize sizeInMicronsField;
        
        private double zField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Imager {
            get {
                return this.imagerField;
            }
            set {
                this.imagerField = value;
            }
        }
        
        /// <remarks/>
        public string ImagingId {
            get {
                return this.imagingIdField;
            }
            set {
                this.imagingIdField = value;
            }
        }
        
        /// <remarks/>
        public string PlateId {
            get {
                return this.plateIdField;
            }
            set {
                this.plateIdField = value;
            }
        }
        
        /// <remarks/>
        public string Drop {
            get {
                return this.dropField;
            }
            set {
                this.dropField = value;
            }
        }
        
        /// <remarks/>
        public ImageInfoImageType ImageType {
            get {
                return this.imageTypeField;
            }
            set {
                this.imageTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ImagedAt {
            get {
                return this.imagedAtField;
            }
            set {
                this.imagedAtField = value;
            }
        }
        
        /// <remarks/>
        public double Zoom {
            get {
                return this.zoomField;
            }
            set {
                this.zoomField = value;
            }
        }
        
        /// <remarks/>
        public Size SizeInPixels {
            get {
                return this.sizeInPixelsField;
            }
            set {
                this.sizeInPixelsField = value;
            }
        }
        
        /// <remarks/>
        public DoubleSize SizeInMicrons {
            get {
                return this.sizeInMicronsField;
            }
            set {
                this.sizeInMicronsField = value;
            }
        }
        
        /// <remarks/>
        public double Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.oppf.ox.ac.uk/xsd/RI/ImageInfo.xsd")]
    public enum ImageInfoImageType {
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        S,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/xsd/RI/ImageInfo.xsd")]
    public partial class Size {
        
        private int heightField;
        
        private int widthField;
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/xsd/RI/ImageInfo.xsd")]
    public partial class DoubleSize {
        
        private double heightField;
        
        private double widthField;
        
        /// <remarks/>
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public double Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
    }
}
