//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.24 at 01:32:15 PM BST 
//


package org.pimslims.crystallization.xml.screen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScreenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScreenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="screenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="screenSupplier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="screenCatNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="screenDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="screenReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="screenNumberOfSolutions" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="solutions" type="{}SolutionList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScreenType", propOrder = {
    "screenName",
    "screenSupplier",
    "screenCatNum",
    "screenDetails",
    "screenReference",
    "screenNumberOfSolutions",
    "solutions"
})
@XmlRootElement(name = "screen")
public class Screen {

    @XmlElement(required = true)
    protected String screenName;
    @XmlElement(required = true)
    protected String screenSupplier;
    @XmlElement(required = true)
    protected String screenCatNum;
    @XmlElement(required = true)
    protected String screenDetails;
    @XmlElement(required = true)
    protected String screenReference;
    @XmlSchemaType(name = "unsignedInt")
    protected long screenNumberOfSolutions;
    @XmlElement(required = true)
    protected SolutionList solutions;

    /**
     * Gets the value of the screenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenName() {
        return screenName;
    }

    /**
     * Sets the value of the screenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenName(String value) {
        this.screenName = value;
    }

    /**
     * Gets the value of the screenSupplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenSupplier() {
        return screenSupplier;
    }

    /**
     * Sets the value of the screenSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenSupplier(String value) {
        this.screenSupplier = value;
    }

    /**
     * Gets the value of the screenCatNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenCatNum() {
        return screenCatNum;
    }

    /**
     * Sets the value of the screenCatNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenCatNum(String value) {
        this.screenCatNum = value;
    }

    /**
     * Gets the value of the screenDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenDetails() {
        return screenDetails;
    }

    /**
     * Sets the value of the screenDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenDetails(String value) {
        this.screenDetails = value;
    }

    /**
     * Gets the value of the screenReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenReference() {
        return screenReference;
    }

    /**
     * Sets the value of the screenReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenReference(String value) {
        this.screenReference = value;
    }

    /**
     * Gets the value of the screenNumberOfSolutions property.
     * 
     */
    public long getScreenNumberOfSolutions() {
        return screenNumberOfSolutions;
    }

    /**
     * Sets the value of the screenNumberOfSolutions property.
     * 
     */
    public void setScreenNumberOfSolutions(long value) {
        this.screenNumberOfSolutions = value;
    }

    /**
     * Gets the value of the solutions property.
     * 
     * @return
     *     possible object is
     *     {@link SolutionList }
     *     
     */
    public SolutionList getSolutions() {
        return solutions;
    }

    /**
     * Sets the value of the solutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SolutionList }
     *     
     */
    public void setSolutions(SolutionList value) {
        this.solutions = value;
    }

}
