/**
 * current-pims-web org.pimslims.bioinf.newtarget BioFormatGuesserTest.java
 * 
 * @author cm65
 * @date 25 Mar 2008
 * 
 *       Protein Information Management System
 * @version: 1.3
 * 
 *           Copyright (c) 2008 cm65
 * 
 * 
 */
package org.pimslims.bioinf.newtarget;

import java.io.IOException;

import junit.framework.Assert;
import junit.framework.TestCase;

import org.pimslims.bioinf.BioInfException;

/**
 * BioFormatGuesserTest
 * 
 */
public class BioFormatGuesserTest extends TestCase {

    /**
     * @param name
     */
    public BioFormatGuesserTest(final String name) {
        super(name);
    }

    /**
     * Test method for
     * {@link org.pimslims.bioinf.newtarget.BioFormatGuesser#getParser(java.lang.String, java.lang.String)}.
     */
    public final void testNoParser() throws IOException, BioInfException {
        final RecordParser parser = BioFormatGuesser.getParser("", "");
        Assert.assertNull(parser);
    }

    public final void testUniProtParser() throws IOException, BioInfException {
        final RecordParser parser = BioFormatGuesser.getParser(UniProtParserTester.swissprotEntry, "");
        Assert.assertTrue(parser instanceof UniProtParser);
    }

    private static final String Q6GS18 =
        "ID   MDM4_HUMAN              Reviewed;         490 AA.\r\n"
            + "AC   O15151; Q32SL2; Q6GS18; Q8IV83;\r\n"
            + "DT   30-MAY-2000, integrated into UniProtKB/Swiss-Prot.\r\n"
            + "DT   27-SEP-2005, sequence version 2.\r\n"
            + "DT   18-APR-2012, entry version 125.\r\n"
            + "DE   RecName: Full=Protein Mdm4;\r\n"
            + "DE   AltName: Full=Double minute 4 protein;\r\n"
            + "DE   AltName: Full=Mdm2-like p53-binding protein;\r\n"
            + "DE   AltName: Full=Protein Mdmx;\r\n"
            + "DE   AltName: Full=p53-binding protein Mdm4;\r\n"
            + "GN   Name=MDM4; Synonyms=MDMX;\r\n"
            + "OS   Homo sapiens (Human).\r\n"
            + "OC   Eukaryota; Metazoa; Chordata; Craniata; Vertebrata; Euteleostomi;\r\n"
            + "OC   Mammalia; Eutheria; Euarchontoglires; Primates; Haplorrhini;\r\n"
            + "OC   Catarrhini; Hominidae; Homo.\r\n"
            + "OX   NCBI_TaxID=9606;\r\n"
            + "RN   [1]\r\n"
            + "RP   NUCLEOTIDE SEQUENCE [MRNA] (ISOFORM 1).\r\n"
            + "RC   TISSUE=Colon tumor;\r\n"
            + "RX   MEDLINE=97369929; PubMed=9226370; DOI=10.1006/geno.1997.4775;\r\n"
            + "RA   Shvarts A., Bazuine M., Dekker P., Ramos Y.F.M., Steegenga W.T.,\r\n"
            + "RA   Merckx G., van Ham R.C.A., van der Houven van Oordt W.,\r\n"
            + "RA   van der Eb A.J., Jochemsen A.G.;\r\n"
            + "RT   \"Isolation and identification of the human homolog of a new p53-\r\n"
            + "RT   binding protein, Mdmx.\";\r\n"
            + "RL   Genomics 43:34-42(1997).\r\n"
            + "RN   [2]\r\n"
            + "RP   NUCLEOTIDE SEQUENCE [MRNA] (ISOFORM HDMX211).\r\n"
            + "RX   PubMed=16266988; DOI=10.1158/0008-5472.CAN-05-0450;\r\n"
            + "RA   Giglio S., Mancini F., Gentiletti F., Sparaco G., Felicioni L.,\r\n"
            + "RA   Barassi F., Martella C., Prodosmo A., Iacovelli S., Buttitta F.,\r\n"
            + "RA   Farsetti A., Soddu S., Marchetti A., Sacchi A., Pontecorvi A.,\r\n"
            + "RA   Moretti F.;\r\n"
            + "RT   \"Identification of an aberrantly spliced form of HDMX in human tumors:\r\n"
            + "RT   a new mechanism for HDM2 stabilization.\";\r\n"
            + "RL   Cancer Res. 65:9687-9694(2005).\r\n"
            + "RN   [3]\r\n"
            + "RP   NUCLEOTIDE SEQUENCE [LARGE SCALE MRNA] (ISOFORM 1).\r\n"
            + "RC   TISSUE=Gastric mucosa;\r\n"
            + "RA   Suzuki Y., Sugano S., Totoki Y., Toyoda A., Takeda T., Sakaki Y.,\r\n"
            + "RA   Tanaka A., Yokoyama S.;\r\n"
            + "RL   Submitted (APR-2005) to the EMBL/GenBank/DDBJ databases.\r\n"
            + "RN   [4]\r\n"
            + "RP   NUCLEOTIDE SEQUENCE [GENOMIC DNA], AND VARIANTS THR-175 AND ILE-406.\r\n"
            + "RG   NIEHS SNPs program;\r\n"
            + "RL   Submitted (DEC-2002) to the EMBL/GenBank/DDBJ databases.\r\n"
            + "RN   [5]\r\n"
            + "RP   NUCLEOTIDE SEQUENCE [LARGE SCALE GENOMIC DNA].\r\n"
            + "RX   PubMed=16710414; DOI=10.1038/nature04727;\r\n"
            + "RA   Gregory S.G., Barlow K.F., McLay K.E., Kaul R., Swarbreck D.,\r\n"
            + "RA   Dunham A., Scott C.E., Howe K.L., Woodfine K., Spencer C.C.A.,\r\n"
            + "RA   Jones M.C., Gillson C., Searle S., Zhou Y., Kokocinski F.,\r\n"
            + "RA   McDonald L., Evans R., Phillips K., Atkinson A., Cooper R., Jones C.,\r\n"
            + "RA   Hall R.E., Andrews T.D., Lloyd C., Ainscough R., Almeida J.P.,\r\n"
            + "RA   Ambrose K.D., Anderson F., Andrew R.W., Ashwell R.I.S., Aubin K.,\r\n"
            + "RA   Babbage A.K., Bagguley C.L., Bailey J., Beasley H., Bethel G.,\r\n"
            + "RA   Bird C.P., Bray-Allen S., Brown J.Y., Brown A.J., Buckley D.,\r\n"
            + "RA   Burton J., Bye J., Carder C., Chapman J.C., Clark S.Y., Clarke G.,\r\n"
            + "RA   Clee C., Cobley V., Collier R.E., Corby N., Coville G.J., Davies J.,\r\n"
            + "RA   Deadman R., Dunn M., Earthrowl M., Ellington A.G., Errington H.,\r\n"
            + "RA   Frankish A., Frankland J., French L., Garner P., Garnett J., Gay L.,\r\n"
            + "RA   Ghori M.R.J., Gibson R., Gilby L.M., Gillett W., Glithero R.J.,\r\n"
            + "RA   Grafham D.V., Griffiths C., Griffiths-Jones S., Grocock R.,\r\n"
            + "RA   Hammond S., Harrison E.S.I., Hart E., Haugen E., Heath P.D.,\r\n"
            + "RA   Holmes S., Holt K., Howden P.J., Hunt A.R., Hunt S.E., Hunter G.,\r\n"
            + "RA   Isherwood J., James R., Johnson C., Johnson D., Joy A., Kay M.,\r\n"
            + "RA   Kershaw J.K., Kibukawa M., Kimberley A.M., King A., Knights A.J.,\r\n"
            + "RA   Lad H., Laird G., Lawlor S., Leongamornlert D.A., Lloyd D.M.,\r\n"
            + "RA   Loveland J., Lovell J., Lush M.J., Lyne R., Martin S.,\r\n"
            + "RA   Mashreghi-Mohammadi M., Matthews L., Matthews N.S.W., McLaren S.,\r\n"
            + "RA   Milne S., Mistry S., Moore M.J.F., Nickerson T., O'Dell C.N.,\r\n"
            + "RA   Oliver K., Palmeiri A., Palmer S.A., Parker A., Patel D., Pearce A.V.,\r\n"
            + "RA   Peck A.I., Pelan S., Phelps K., Phillimore B.J., Plumb R., Rajan J.,\r\n"
            + "RA   Raymond C., Rouse G., Saenphimmachak C., Sehra H.K., Sheridan E.,\r\n"
            + "RA   Shownkeen R., Sims S., Skuce C.D., Smith M., Steward C.,\r\n"
            + "RA   Subramanian S., Sycamore N., Tracey A., Tromans A., Van Helmond Z.,\r\n"
            + "RA   Wall M., Wallis J.M., White S., Whitehead S.L., Wilkinson J.E.,\r\n"
            + "RA   Willey D.L., Williams H., Wilming L., Wray P.W., Wu Z., Coulson A.,\r\n"
            + "RA   Vaudin M., Sulston J.E., Durbin R.M., Hubbard T., Wooster R.,\r\n"
            + "RA   Dunham I., Carter N.P., McVean G., Ross M.T., Harrow J., Olson M.V.,\r\n"
            + "RA   Beck S., Rogers J., Bentley D.R.;\r\n"
            + "RT   \"The DNA sequence and biological annotation of human chromosome 1.\";\r\n"
            + "RL   Nature 441:315-321(2006).\r\n"
            + "RN   [6]\r\n"
            + "RP   NUCLEOTIDE SEQUENCE [LARGE SCALE MRNA] (ISOFORM 1).\r\n"
            + "RC   TISSUE=Testis;\r\n"
            + "RX   PubMed=15489334; DOI=10.1101/gr.2596504;\r\n"
            + "RG   The MGC Project Team;\r\n"
            + "RT   \"The status, quality, and expansion of the NIH full-length cDNA\r\n"
            + "RT   project: the Mammalian Gene Collection (MGC).\";\r\n"
            + "RL   Genome Res. 14:2121-2127(2004).\r\n"
            + "RN   [7]\r\n"
            + "RP   ALTERNATIVE SPLICING (ISOFORMS 2 AND 3).\r\n"
            + "RX   PubMed=12761890; DOI=10.1002/jcb.10535;\r\n"
            + "RA   Rallapalli R., Strachan G., Tuan R.S., Hall D.J.;\r\n"
            + "RT   \"Identification of a domain within MDMX-S that is responsible for its\r\n"
            + "RT   high affinity interaction with p53 and high-level expression in\r\n"
            + "RT   mammalian cells.\";\r\n"
            + "RL   J. Cell. Biochem. 89:563-575(2003).\r\n"
            + "RN   [8]\r\n"
            + "RP   MUTAGENESIS OF CYS-437.\r\n"
            + "RX   MEDLINE=20076498; PubMed=10608892; DOI=10.1074/jbc.274.53.38189;\r\n"
            + "RA   Sharp D.A., Kratowicz S.A., Sank M.J., George D.L.;\r\n"
            + "RT   \"Stabilization of the MDM2 oncoprotein by interaction with the\r\n"
            + "RT   structurally related MDMX protein.\";\r\n"
            + "RL   J. Biol. Chem. 274:38189-38196(1999).\r\n"
            + "RN   [9]\r\n"
            + "RP   FUNCTION IN TP53 ACTIVATION, PHOSPHORYLATION AT SER-342 AND SER-367 BY\r\n"
            + "RP   CHEK2, UBIQUITINATION, AND INTERACTION WITH MDM2.\r\n"
            + "RX   PubMed=16163388; DOI=10.1038/sj.emboj.7600812;\r\n"
            + "RA   Chen L., Gilkes D.M., Pan Y., Lane W.S., Chen J.;\r\n"
            + "RT   \"ATM and Chk2-dependent phosphorylation of MDMX contribute to p53\r\n"
            + "RT   activation after DNA damage.\";\r\n"
            + "RL   EMBO J. 24:3411-3422(2005).\r\n"
            + "RN   [10]\r\n"
            + "RP   FUNCTION IN TP53 ACTIVATION, PHOSPHORYLATION AT SER-367 BY CHEK1, AND\r\n"
            + "RP   INTERACTION WITH YWHAG.\r\n"
            + "RX   PubMed=16511572; DOI=10.1038/sj.emboj.7601010;\r\n"
            + "RA   Jin Y., Dai M.S., Lu S.Z., Xu Y., Luo Z., Zhao Y., Lu H.;\r\n"
            + "RT   \"14-3-3gamma binds to MDMX that is phosphorylated by UV-activated\r\n"
            + "RT   Chk1, resulting in p53 activation.\";\r\n"
            + "RL   EMBO J. 25:1207-1218(2006).\r\n"
            + "RN   [11]\r\n"
            + "RP   INTERACTION WITH USP2 AND MDM2, INDUCTION, UBIQUITINATION, AND\r\n"
            + "RP   DEUBIQUITINATION BY USP2.\r\n"
            + "RX   PubMed=19838211; DOI=10.1038/onc.2009.330;\r\n"
            + "RA   Allende-Vega N., Sparks A., Lane D.P., Saville M.K.;\r\n"
            + "RT   \"MdmX is a substrate for the deubiquitinating enzyme USP2a.\";\r\n"
            + "RL   Oncogene 29:432-441(2010).\r\n"
            + "RN   [12]\r\n"
            + "RP   MASS SPECTROMETRY.\r\n"
            + "RC   TISSUE=Mammary cancer;\r\n"
            + "RX   MEDLINE=21829512; PubMed=11840567;\r\n"
            /* */+ "RX   DOI=10.1002/1615-9861(200202)2:2<212::AID-PROT212>3.0.CO;2-H;\r\n"
            + "RA   Harris R.A., Yang A., Stein R.C., Lucy K., Brusten L., Herath A.,\r\n"
            + "RA   Parekh R., Waterfield M.D., O'Hare M.J., Neville M.A., Page M.J.,\r\n"
            + "RA   Zvelebil M.J.;\r\n"
            + "RT   \"Cluster analysis of an extensive human breast cancer cell line\r\n"
            + "RT   protein expression map database.\";\r\n"
            + "RL   Proteomics 2:212-223(2002).\r\n"
            + "RN   [13]\r\n"
            + "RP   STRUCTURE BY NMR OF 300-340.\r\n"
            + "RG   RIKEN structural genomics initiative (RSGI);\r\n"
            + "RT   \"Solution structure of the ZF-RANBP domain of p53-binding protein\r\n"
            + "RT   MDM4.\";\r\n"
            + "RL   Submitted (NOV-2005) to the PDB data bank.\r\n"
            + "CC   -!- FUNCTION: Inhibits p53/TP53- and TP73/p73-mediated cell cycle\r\n"
            + "CC       arrest and apoptosis by binding its transcriptional activation\r\n"
            + "CC       domain. Inhibits degradation of MDM2. Can reverse MDM2-targeted\r\n"
            + "CC       degradation of TP53 while maintaining suppression of TP53\r\n"
            + "CC       transactivation and apoptotic functions.\r\n"
            + "CC   -!- SUBUNIT: Interacts with MDM2, TP53, TP73 and USP2. Found in a\r\n"
            + "CC       trimeric complex with UPB2, MDM2 and MDM4. Interacts\r\n"
            + "CC       (phosphorylated) with YWHAG; negatively regulates MDM4 activity\r\n"
            + "CC       toward TP53.\r\n"
            + "CC   -!- INTERACTION:\r\n"
            + "CC       Q00987:MDM2; NbExp=4; IntAct=EBI-398437, EBI-389668;\r\n"
            + "CC       P04637:TP53; NbExp=3; IntAct=EBI-398437, EBI-366083;\r\n"
            + "CC   -!- SUBCELLULAR LOCATION: Nucleus.\r\n"
            + "CC   -!- ALTERNATIVE PRODUCTS:\r\n"
            + "CC       Event=Alternative splicing; Named isoforms=4;\r\n"
            + "CC         Comment=Additional isoforms seem to exist;\r\n"
            + "CC       Name=1;\r\n"
            + "CC         IsoId=O15151-1; Sequence=Displayed;\r\n"
            + "CC       Name=2; Synonyms=MDMX-S;\r\n"
            + "CC         IsoId=O15151-2; Sequence=VSP_035669;\r\n"
            + "CC         Note=No experimental confirmation available;\r\n"
            + "CC       Name=3; Synonyms=MDMX;\r\n"
            + "CC         IsoId=O15151-3; Sequence=VSP_035670;\r\n"
            + "CC         Note=No experimental confirmation available;\r\n"
            + "CC       Name=HDMX211;\r\n"
            + "CC         IsoId=O15151-4; Sequence=VSP_042563;\r\n"
            + "CC         Note=Cancer-specific isoform, may counteract MDM2/MDM4-mediated\r\n"
            + "CC         p53 degradation;\r\n"
            + "CC   -!- TISSUE SPECIFICITY: Expressed in all tissues tested with high\r\n"
            + "CC       levels in thymus.\r\n"
            + "CC   -!- INDUCTION: Down-regulated by cisplatin (at protein level).\r\n"
            + "CC   -!- DOMAIN: Region I is sufficient for binding TP53 and inhibiting its\r\n"
            + "CC       G1 arrest and apoptosis functions. It also binds TP73. Region II\r\n"
            + "CC       contains most of a central acidic region and a putative C4-type\r\n"
            + "CC       zinc finger. The RING finger domain which coordinates two\r\n"
            + "CC       molecules of zinc mediates the heterooligomerization with MDM2.\r\n"
            + "CC   -!- PTM: Phosphorylated. Phosphorylation at Ser-367 promotes\r\n"
            + "CC       interaction with YWHAG and subsequent ubiquitination and\r\n"
            + "CC       degradation. Phosphorylation at Ser-342 also induces\r\n"
            + "CC       ubiquitination and degradation but to a lower extent.\r\n"
            + "CC   -!- PTM: Ubiquitinated and degraded by MDM2. Deubiquitination by USP2\r\n"
            + "CC       on the other hand stabilizes the MDM4 protein.\r\n"
            + "CC   -!- MASS SPECTROMETRY: Mass=54863.3; Method=MALDI; Range=1-490;\r\n"
            + "CC       Source=PubMed:11840567;\r\n"
            + "CC   -!- SIMILARITY: Belongs to the MDM2/MDM4 family.\r\n"
            + "CC   -!- SIMILARITY: Contains 1 RanBP2-type zinc finger.\r\n"
            + "CC   -!- SIMILARITY: Contains 1 RING-type zinc finger.\r\n"
            + "CC   -!- SIMILARITY: Contains 1 SWIB domain.\r\n"
            + "CC   -!- WEB RESOURCE: Name=NIEHS-SNPs;\r\n"
            + "CC       URL=\"http://egp.gs.washington.edu/data/mdm4/\";\r\n"
            + "CC   -----------------------------------------------------------------------\r\n"
            + "CC   Copyrighted by the UniProt Consortium, see http://www.uniprot.org/terms\r\n"
            + "CC   Distributed under the Creative Commons Attribution-NoDerivs License\r\n"
            + "CC   -----------------------------------------------------------------------\r\n"
            + "DR   EMBL; AF007111; AAB62928.1; -; mRNA.\r\n"
            + "DR   EMBL; AY923176; AAY22054.1; -; mRNA.\r\n"
            + "DR   EMBL; AK223228; BAD96948.1; -; mRNA.\r\n"
            + "DR   EMBL; AY207458; AAO13494.1; -; Genomic_DNA.\r\n"
            + "DR   EMBL; AL512306; CAI14100.1; -; Genomic_DNA.\r\n"
            + "DR   EMBL; BC067299; AAH67299.1; -; mRNA.\r\n"
            + "DR   IPI; IPI00005170; -.\r\n"
            + "DR   IPI; IPI00655963; -.\r\n"
            + "DR   IPI; IPI00914644; -.\r\n"
            + "DR   IPI; IPI00914667; -.\r\n"
            + "DR   RefSeq; NP_001191101.1; NM_001204172.1.\r\n"
            + "DR   RefSeq; NP_002384.2; NM_002393.4.\r\n"
            + "DR   UniGene; Hs.497492; -.\r\n"
            + "DR   PDB; 2CR8; NMR; -; A=300-339.\r\n"
            + "DR   PDB; 2VJE; X-ray; 2.20 A; B/D=428-490.\r\n"
            + "DR   PDB; 2VJF; X-ray; 2.30 A; B/D=428-490.\r\n"
            + "DR   PDB; 2VYR; X-ray; 2.00 A; A/B/C/D=16-116.\r\n"
            + "DR   PDB; 3DAB; X-ray; 1.90 A; A/C/E/G=23-111.\r\n"
            + "DR   PDB; 3EQY; X-ray; 1.63 A; A/B=24-108.\r\n"
            + "DR   PDB; 3FDO; X-ray; 1.40 A; A=23-111.\r\n"
            + "DR   PDB; 3FE7; X-ray; 1.35 A; A=14-111.\r\n"
            + "DR   PDB; 3FEA; X-ray; 1.33 A; A=14-111.\r\n"
            + "DR   PDB; 3JZO; X-ray; 1.80 A; A=23-111.\r\n"
            + "DR   PDB; 3JZP; X-ray; 1.74 A; A=23-111.\r\n"
            + "DR   PDB; 3JZQ; X-ray; 1.80 A; A/B=23-111.\r\n"
            + "DR   PDB; 3LBJ; X-ray; 1.50 A; E=23-111.\r\n"
            + "DR   PDBsum; 2CR8; -.\r\n"
            + "DR   PDBsum; 2VJE; -.\r\n"
            + "DR   PDBsum; 2VJF; -.\r\n"
            + "DR   PDBsum; 2VYR; -.\r\n"
            + "DR   PDBsum; 3DAB; -.\r\n"
            + "DR   PDBsum; 3EQY; -.\r\n"
            + "DR   PDBsum; 3FDO; -.\r\n"
            + "DR   PDBsum; 3FE7; -.\r\n"
            + "DR   PDBsum; 3FEA; -.\r\n"
            + "DR   PDBsum; 3JZO; -.\r\n"
            + "DR   PDBsum; 3JZP; -.\r\n"
            + "DR   PDBsum; 3JZQ; -.\r\n"
            + "DR   PDBsum; 3LBJ; -.\r\n"
            + "DR   ProteinModelPortal; O15151; -.\r\n"
            + "DR   SMR; O15151; 26-108, 301-344, 429-490.\r\n"
            + "DR   DIP; DIP-24199N; -.\r\n"
            + "DR   IntAct; O15151; 3.\r\n"
            + "DR   MINT; MINT-113852; -.\r\n"
            + "DR   STRING; O15151; -.\r\n"
            + "DR   PhosphoSite; O15151; -.\r\n"
            + "DR   PRIDE; O15151; -.\r\n"
            + "DR   Ensembl; ENST00000367182; ENSP00000356150; ENSG00000198625.\r\n"
            + "DR   Ensembl; ENST00000367183; ENSP00000356151; ENSG00000198625.\r\n"
            + "DR   GeneID; 4194; -.\r\n"
            + "DR   KEGG; hsa:4194; -.\r\n"
            + "DR   UCSC; uc001hba.3; human.\r\n"
            + "DR   CTD; 4194; -.\r\n"
            + "DR   GeneCards; GC01P204486; -.\r\n"
            + "DR   H-InvDB; HIX0019963; -.\r\n"
            + "DR   HGNC; HGNC:6974; MDM4.\r\n"
            + "DR   HPA; HPA018919; -.\r\n"
            + "DR   MIM; 602704; gene.\r\n"
            + "DR   neXtProt; NX_O15151; -.\r\n"
            + "DR   PharmGKB; PA30719; -.\r\n"
            + "DR   eggNOG; NOG46328; -.\r\n"
            + "DR   GeneTree; ENSGT00530000063539; -.\r\n"
            + "DR   HOGENOM; HBG717854; -.\r\n"
            + "DR   HOVERGEN; HBG013472; -.\r\n"
            + "DR   InParanoid; O15151; -.\r\n"
            + "DR   KO; K10127; -.\r\n"
            + "DR   OMA; QETISSM; -.\r\n"
            + "DR   OrthoDB; EOG4CZBFT; -.\r\n"
            + "DR   PhylomeDB; O15151; -.\r\n"
            + "DR   EvolutionaryTrace; O15151; -.\r\n"
            + "DR   NextBio; 16538; -.\r\n"
            + "DR   PMAP-CutDB; O15151; -.\r\n"
            + "DR   ArrayExpress; O15151; -.\r\n"
            + "DR   Bgee; O15151; -.\r\n"
            + "DR   CleanEx; HS_MDM4; -.\r\n"
            + "DR   Genevestigator; O15151; -.\r\n"
            + "DR   GermOnline; ENSG00000198625; Homo sapiens.\r\n"
            + "DR   GO; GO:0005634; C:nucleus; NAS:UniProtKB.\r\n"
            + "DR   GO; GO:0019899; F:enzyme binding; IPI:UniProtKB.\r\n"
            + "DR   GO; GO:0008270; F:zinc ion binding; TAS:UniProtKB.\r\n"
            + "DR   GO; GO:0006915; P:apoptotic process; IEP:UniProtKB.\r\n"
            + "DR   GO; GO:0008283; P:cell proliferation; IEP:UniProtKB.\r\n"
            + "DR   GO; GO:0071456; P:cellular response to hypoxia; IEP:UniProtKB.\r\n"
            + "DR   GO; GO:0045023; P:G0 to G1 transition; IEP:UniProtKB.\r\n"
            + "DR   GO; GO:0043066; P:negative regulation of apoptotic process; IEA:InterPro.\r\n"
            + "DR   GO; GO:0071157; P:negative regulation of cell cycle arrest; IEA:InterPro.\r\n"
            + "DR   GO; GO:0008285; P:negative regulation of cell proliferation; TAS:ProtInc.\r\n"
            + "DR   GO; GO:0042177; P:negative regulation of protein catabolic process; IMP:UniProtKB.\r\n"
            + "DR   GO; GO:0000122; P:negative regulation of transcription from RNA polymerase II promoter; IDA:UniProtKB.\r\n"
            + "DR   GO; GO:0006461; P:protein complex assembly; IDA:UniProtKB.\r\n"
            + "DR   GO; GO:0050821; P:protein stabilization; IEP:UniProtKB.\r\n"
            + "DR   InterPro; IPR016495; p53_neg-reg_MDM_2/4.\r\n"
            + "DR   InterPro; IPR003121; SWIB_MDM2_domain.\r\n" + "DR   InterPro; IPR001876; Znf_RanBP2.\r\n"
            + "DR   InterPro; IPR001841; Znf_RING.\r\n" + "DR   Pfam; PF02201; SWIB; 1.\r\n"
            + "DR   Pfam; PF00641; zf-RanBP; 1.\r\n" + "DR   PIRSF; PIRSF006748; p53_MDM_2/4; 1.\r\n"
            + "DR   SMART; SM00184; RING; 1.\r\n" + "DR   SMART; SM00547; ZnF_RBZ; 1.\r\n"
            + "DR   SUPFAM; SSF47592; MDM2; 1.\r\n" + "DR   PROSITE; PS01358; ZF_RANBP2_1; 1.\r\n"
            + "DR   PROSITE; PS50199; ZF_RANBP2_2; 1.\r\n"
            + "DR   PROSITE; PS00518; ZF_RING_1; FALSE_NEG.\r\n" + "DR   PROSITE; PS50089; ZF_RING_2; 1.\r\n"
            + "PE   1: Evidence at protein level;\r\n"
            + "KW   3D-structure; Alternative splicing; Complete proteome; Metal-binding;\r\n"
            + "KW   Nucleus; Phosphoprotein; Polymorphism; Reference proteome;\r\n"
            + "KW   Ubl conjugation; Zinc; Zinc-finger.\r\n"
            + "FT   CHAIN         1    490       Protein Mdm4.\r\n"
            + "FT                                /FTId=PRO_0000157336.\r\n"
            + "FT   DOMAIN       26    106       SWIB.\r\n"
            + "FT   ZN_FING     300    329       RanBP2-type.\r\n"
            + "FT   ZN_FING     437    478       RING-type.\r\n"
            + "FT   REGION      246    332       Region II.\r\n"
            + "FT   REGION      393    490       Necessary for interaction with UBP2.\r\n"
            + "FT   MOTIF       442    445       Nuclear localization signal (Potential).\r\n"
            + "FT   COMPBIAS    243    308       Asp/Glu-rich (acidic).\r\n"
            + "FT   MOD_RES     342    342       Phosphoserine; by CHEK2.\r\n"
            + "FT   MOD_RES     367    367       Phosphoserine; by CHEK1 and CHEK2.\r\n"
            + "FT   VAR_SEQ      27    352       Missing (in isoform HDMX211).\r\n"
            + "FT                                /FTId=VSP_042563.\r\n"
            + "FT   VAR_SEQ     109    490       LATATTDAAQTLALAQDHSMDIPSQDQLKQSAEESSTSRKR\r\n"
            + "FT                                TTEDDIPTLPTSEHKCIHSREDEDLIENLAQDETSRLDLGF\r\n"
            + "FT                                EEWDVAGLPWWFLGNLRSNYTPRSNGSTDLQTNQDVGTAIV\r\n"
            + "FT                                SDTTDDLWFLNESVSEQLGVGIKVEAADTEQTSEEVGKVSD\r\n"
            + "FT                                KKVIEVGKNDDLEDSKSLSDDTDVEVTSEDEWQCTECKKFN\r\n"
            + "FT                                SPSKRYCFRCWALRKDWYSDCSKLTHSLSTSDITAIPEKEN\r\n"
            + "FT                                EGNDVPDCRRTISAPVVRPKDAYIKKENSKLFDPCNSVEFL\r\n"
            + "FT                                DLAHSSESQETISSMGEQLDNLSEQRTDTENMEDCQNLLKP\r\n"
            + "FT                                CSLCEKRPRDGNIIHGRTGHLVTCFHCARRLKKAGASCPIC\r\n"
            + "FT                                KKEIQLVIKVFIA -> SASNNTARCNRILQSQKKN (in\r\n"
            + "FT                                isoform 2).\r\n"
            + "FT                                /FTId=VSP_035669.\r\n"
            + "FT   VAR_SEQ     109    490       LATATTDAAQTLALAQDHSMDIPSQDQLKQSAEESSTSRKR\r\n"
            + "FT                                TTEDDIPTLPTSEHKCIHSREDEDLIENLAQDETSRLDLGF\r\n"
            + "FT                                EEWDVAGLPWWFLGNLRSNYTPRSNGSTDLQTNQDVGTAIV\r\n"
            + "FT                                SDTTDDLWFLNESVSEQLGVGIKVEAADTEQTSEEVGKVSD\r\n"
            + "FT                                KKVIEVGKNDDLEDSKSLSDDTDVEVTSEDEWQCTECKKFN\r\n"
            + "FT                                SPSKRYCFRCWALRKDWYSDCSKLTHSLSTSDITAIPEKEN\r\n"
            + "FT                                EGNDVPDCRRTISAPVVRPKDAYIKKENSKLFDPCNSVEFL\r\n"
            + "FT                                DLAHSSESQETISSMGEQLDNLSEQRTDTENMEDCQNLLKP\r\n"
            + "FT                                CSLCEKRPRDGNIIHGRTGHLVTCFHCARRLKKAGASCPIC\r\n"
            + "FT                                KKEIQLVIKVFIA -> SASNNTDAAQTLALAQDHT (in\r\n"
            + "FT                                isoform 3).\r\n"
            + "FT                                /FTId=VSP_035670.\r\n"
            + "FT   VARIANT     175    175       I -> T (in dbSNP:rs4252716).\r\n"
            + "FT                                /FTId=VAR_017106.\r\n"
            + "FT   VARIANT     406    406       T -> I (in dbSNP:rs4252741).\r\n"
            + "FT                                /FTId=VAR_017107.\r\n"
            + "FT   MUTAGEN     437    437       C->G: Fails to interact with MDM2.\r\n"
            + "FT   CONFLICT     94     94       D -> N (in Ref. 1; AAB62928).\r\n"
            + "FT   STRAND       27     29\r\n" + "FT   HELIX        31     39\r\n"
            + "FT   HELIX        49     55\r\n" + "FT   HELIX        59     62\r\n"
            + "FT   STRAND       70     75\r\n" + "FT   STRAND       89     91\r\n"
            + "FT   HELIX        96    105\r\n" + "FT   STRAND      307    309\r\n"
            + "FT   TURN        321    323\r\n" + "FT   STRAND      431    435\r\n"
            + "FT   STRAND      437    443\r\n" + "FT   STRAND      445    460\r\n"
            + "FT   HELIX       461    469\r\n" + "FT   STRAND      470    473\r\n"
            + "FT   STRAND      475    489\r\n"
            + "SQ   SEQUENCE   490 AA;  54864 MW;  415E6FA5A0C69857 CRC64;\r\n"
            + "     MTSFSTSAQC STSDSACRIS PGQINQVRPK LPLLKILHAA GAQGEMFTVK EVMHYLGQYI\r\n"
            + "     MVKQLYDQQE QHMVYCGGDL LGELLGRQSF SVKDPSPLYD MLRKNLVTLA TATTDAAQTL\r\n"
            + "     ALAQDHSMDI PSQDQLKQSA EESSTSRKRT TEDDIPTLPT SEHKCIHSRE DEDLIENLAQ\r\n"
            + "     DETSRLDLGF EEWDVAGLPW WFLGNLRSNY TPRSNGSTDL QTNQDVGTAI VSDTTDDLWF\r\n"
            + "     LNESVSEQLG VGIKVEAADT EQTSEEVGKV SDKKVIEVGK NDDLEDSKSL SDDTDVEVTS\r\n"
            + "     EDEWQCTECK KFNSPSKRYC FRCWALRKDW YSDCSKLTHS LSTSDITAIP EKENEGNDVP\r\n"
            + "     DCRRTISAPV VRPKDAYIKK ENSKLFDPCN SVEFLDLAHS SESQETISSM GEQLDNLSEQ\r\n"
            + "     RTDTENMEDC QNLLKPCSLC EKRPRDGNII HGRTGHLVTC FHCARRLKKA GASCPICKKE\r\n"
            + "     IQLVIKVFIA\r\n" + "//";

    public final void testQ6GS18() throws IOException, BioInfException {
        new UniProtParser(BioFormatGuesserTest.Q6GS18);
        final RecordParser parser = BioFormatGuesser.getParser(BioFormatGuesserTest.Q6GS18, "");
        Assert.assertTrue(parser instanceof UniProtParser);

    }

    /**
     * Test method for {@link org.pimslims.bioinf.newtarget.BioFormatGuesser#canParse(java.lang.String)}.
     */
    public final void testCantParse() {
        final boolean canParse = BioFormatGuesser.canParse("");
        Assert.assertFalse(canParse);
    }

    public final void testCantParseUniProt() {
        final boolean canParse = BioFormatGuesser.canParse(UniProtParserTester.swissprotEntry);
        Assert.assertTrue(canParse);
    }

    private static final String EMBL_RECORD =
        "ID   AAC64374; SV 1; linear; genomic DNA; STD; FUN; 1149 BP.\r\n" + "XX\r\n" + "PA   U68715.1\r\n"
            + "XX\r\n" + "DE   Botryotinia fuckeliana endopolygalacturonase 1\r\n" + "XX\r\n"
            + "OS   Botryotinia fuckeliana\r\n"
            + "OC   Eukaryota; Fungi; Dikarya; Ascomycota; Pezizomycotina; Leotiomycetes;\r\n"
            + "OC   Helotiales; Sclerotiniaceae; Botryotinia.\r\n" + "OX   NCBI_TaxID=40559;\r\n" + "XX\r\n"
            + "FH   Key             Location/Qualifiers\r\n" + "FH\r\n" + "FT   source          1..1149\r\n"
            + "FT                   /organism=\"Botryotinia fuckeliana\"\r\n"
            + "FT                   /isolate=\"SAS56\"\r\n"
            + "FT                   /mol_type=\"genomic DNA\"\r\n"
            + "FT   CDS             U68715.1:867..2015\r\n" + "FT                   /codon_start=1\r\n"
            + "FT                   /gene=\"BcPGA1\"\r\n"
            + "FT                   /product=\"endopolygalacturonase 1\"\r\n"
            + "FT                   /note=\"BcPG1\"\r\n" + "FT                   /db_xref=\"GOA:O94100\"\r\n"
            + "FT                   /db_xref=\"HSSP:1IB4\"\r\n"
            + "FT                   /db_xref=\"InterPro:IPR000743\"\r\n"
            + "FT                   /db_xref=\"InterPro:IPR006626\"\r\n"
            + "FT                   /db_xref=\"InterPro:IPR011050\"\r\n"
            + "FT                   /db_xref=\"InterPro:IPR012334\"\r\n"
            + "FT                   /db_xref=\"UniProtKB/TrEMBL:O94100\"\r\n"
            + "FT                   /protein_id=\"AAC64374.1\"\r\n"
            + "FT                   /translation=\"MVQLLSMASGLLALSAIVSAAPAPAPTAAPNPAEALAAIEQRGTA\r\n"
            + "FT                   CTFSGSGGAAAASKSKASCATIVLSALSVPSGTTLDLTGLKSGTQVIFEGTTTFGYEEW\r\n"
            + "FT                   SGPLFSVSGTDITVKGASGSKLDGQGAKYWDGKGTNGGKTKPKFFYAHSLKGKSTISGI\r\n"
            + "FT                   NILNSPVQVFSINGASGLTLSNINIDNSAGDAGSLGHNTDAFDVGSSSDITISGAVVKN\r\n"
            + "FT                   QDDCLAINSGTGITFTGGTCSGGHGLSIGSVGGRSDNTVSDIIIESSTVKNSANGVRIK\r\n"
            + "FT                   TVSGATGSVSGVTYKDITLSGITSYGVVVQQDYKNGSPTGTPTSGVPITDVTFSNVKGT\r\n"
            + "FT                   VASGATNVYVLCAKCSGWSWDVSVSGGKTSSKCAGLPSGVKC\"\r\n" + "XX\r\n"
            + "SQ   Sequence 1149 BP; 236 A; 367 C; 257 G; 289 T; 0 other; 4251996525 CRC32;\r\n"
            + "     atggttcaac ttctctcaat ggcctccggc ctccttgcgc tgagcgcaat cgtctctgct        60\r\n"
            + "     gctccagcac cagcaccaac cgcagcacca aacccagctg aggctctcgc cgctatcgag       120\r\n"
            + "     caacgtggta ccgcctgtac cttctccgga tctggcggtg ctgcagccgc ttccaagtcc       180\r\n"
            + "     aaggcttcct gcgccaccat cgtcctcagc gccctctccg tcccatccgg tactactctt       240\r\n"
            + "     gacttgactg gcctcaagtc cggcacccag gtcatcttcg agggtaccac caccttcggt       300\r\n"
            + "     tacgaagaat ggtccggtcc tctcttctct gtctccggaa ctgacatcac tgtcaagggt       360\r\n"
            + "     gcctccggca gcaagcttga tggtcaagga gccaagtact gggatggtaa gggaaccaac       420\r\n"
            + "     ggtggaaaga ccaagccaaa gttcttctac gcccactcct tgaagggtaa atcaacaatc       480\r\n"
            + "     tctggtatca acatcttgaa ctctccagtt caagtcttct ccatcaacgg tgcttccggt       540\r\n"
            + "     cttactctct ccaacatcaa cattgacaac tctgctggag atgctggttc ccttggccac       600\r\n"
            + "     aacaccgatg ctttcgatgt tggttcctcc agcgatatca ccatctccgg tgccgtcgtt       660\r\n"
            + "     aagaaccaag atgactgtct cgctatcaac tccggtactg gtattacctt caccggtgga       720\r\n"
            + "     acctgttccg gtggtcacgg tctctccatc ggatctgtcg gtggacgttc cgacaacact       780\r\n"
            + "     gtctccgata tcatcatcga atcatctact gtcaagaact ctgccaacgg tgtccgtatc       840\r\n"
            + "     aagactgtct ccggtgccac tggatccgtc tccggcgtta cctacaaaga catcaccctc       900\r\n"
            + "     tccggcatta catcctacgg tgttgtcgtt caacaagatt acaagaacgg ttccccaact       960\r\n"
            + "     ggtaccccaa cttcaggtgt ccccatcact gatgtcactt tctccaacgt caagggtacc      1020\r\n"
            + "     gtcgcctccg gtgccaccaa tgtctacgtt ctttgcgcca agtgctctgg ctggtcttgg      1080\r\n"
            + "     gatgtcagtg ttagcggtgg taagacctcc agcaagtgtg ctggtctccc atctggtgtc      1140\r\n"
            + "     aagtgttaa                                                              1149\r\n" + "//";

    public void testIsEMBL() {
        Assert.assertFalse(ParserUtility.isEMBL(""));
        Assert.assertTrue(ParserUtility.isEMBL(BioFormatGuesserTest.EMBL_RECORD));
    }
}
