<%--
Create.jsp works with Create servlet
It displays the generated by Create servlet html in appropriate html mockups
It also main control the generation workflow.
It includes the output from other JSP to actually display attributes
(CreateAttributes) and roles (CreateRoles).

Optional elements are:
"reqAttr" instanceof ArrayList  form elements as AttributeToHTML instances (required attributes)
"optAttr" instanceof ArrayList  form elements as AttributeToHTML instances (optional attributes)
"reqRoles" instanceof ArrayList roles as AttributeToHTML instances (required roles)
"errorMessages" instanceof Map  error messages
For more information @see org.pimslims.servlet.CustomCreate 

Author: Peter Troshin
Date: February 2006
--%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="pimsForm" tagdir="/WEB-INF/tags/pimsForm" %>
<%@ taglib prefix="pimsWidget" tagdir="/WEB-INF/tags/pimsWidget" %>

<%--Caller must provide this --%>
<jsp:useBean id="metaclass" scope="request" type="org.pimslims.metamodel.MetaClass" />

<jsp:useBean id="javascript" scope="request" type="java.lang.String" />
<jsp:useBean id="headerTitle" scope="request" type="java.lang.String" />
<jsp:useBean id="pathInfo" scope="request" type="java.lang.String" />

<jsp:include page="/JSP/core/Header.jsp">
    <jsp:param name="HeaderName" value='Create a new User Group' />
</jsp:include>


<jsp:scriptlet>
  String style = "even";
  pageContext.setAttribute("style", style);
</jsp:scriptlet>

<p class="help">A User Group can be used to set the right to read, create, update and delete records.<br />


<c:if test="${! empty errorMessages['notProvided']}">
    <div class="formrow" style="text-align:left">
        <span style="color:red;font-weight:bold">
        To create a
        ${metaclass.alias}, you first need to specify a
        ${errorMessages['notProvided']}. Please click one of the links below to search for an
        existing ${errorMessages['notProvided']} or create a new one.
        </span>
    </div>
</c:if>

<%-- There may be an error for the attribute does not displayed on the page show it here  --%>
<c:if test="${! empty errorMessages['missedErrorFields']}">
    <div class="formrow" style="text-align:left">
        <span style="color:red;font-weight:bold">
		There has been the following errors: 
		<c:forEach items="${errorMessages['missedErrorFields']}" var="fieldsNames">
			<br />The ${fieldsNames} - ${errorMessages[fieldsNames]}	
		</c:forEach>
        </span>
    </div>
</c:if>


<pimsWidget:box title="Details" initialState="fixed" >
<pimsForm:form  action="/Create/${pathInfo}" mode="edit" method="post">
<pimsForm:formBlock>

<input type="hidden" name="METACLASSNAME" value="${metaclass.metaClassName}"/>

<!-- If this is attribute -->

<%-- Iterate other required attributes --%>
<c:set var="Attributes" value="${reqAttr}" scope="request"/>
<jsp:include page="/JSP/create/CreateAttributes.jsp"></jsp:include>

<%-- Iterate other optional attributes --%>
<c:set var="Attributes" value="${optAttr}" scope="request"/>
<jsp:include page="/JSP/create/CreateAttributes.jsp"></jsp:include>



<input name="_OWNER" value="reference" type="hidden" />

<!-- Pass the parameters -->
<input type="hidden" name="parametersString"  value="${parameters}" />

<input class="submit button"  type="submit" value="Save" onclick="dontWarn(); return checkSequence();"/>
</pimsForm:formBlock></pimsForm:form></pimsWidget:box>



<!-- javascript -->
${javascript}

<jsp:include page="/JSP/core/Footer.jsp" />
