//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.24 at 12:41:30 AM BST 
//


package org.pimslims.crystallization.xml.rmxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ingredient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ingredient">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aliases" type="{}aliases" minOccurs="0"/>
 *         &lt;element name="casNumbers" type="{}casNumbers" minOccurs="0"/>
 *         &lt;element name="types" type="{}types"/>
 *         &lt;element name="bufferData" type="{}bufferData" minOccurs="0"/>
 *         &lt;element name="stocks" type="{}stocks"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ingredient", propOrder = {

})
public class Ingredient {

    @XmlElement(required = true)
    protected String name;
    protected String shortName;
    protected Aliases aliases;
    protected CasNumbers casNumbers;
    @XmlElement(required = true)
    protected Types types;
    protected BufferData bufferData;
    @XmlElement(required = true)
    protected Stocks stocks;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link Aliases }
     *     
     */
    public Aliases getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aliases }
     *     
     */
    public void setAliases(Aliases value) {
        this.aliases = value;
    }

    /**
     * Gets the value of the casNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link CasNumbers }
     *     
     */
    public CasNumbers getCasNumbers() {
        return casNumbers;
    }

    /**
     * Sets the value of the casNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link CasNumbers }
     *     
     */
    public void setCasNumbers(CasNumbers value) {
        this.casNumbers = value;
    }

    /**
     * Gets the value of the types property.
     * 
     * @return
     *     possible object is
     *     {@link Types }
     *     
     */
    public Types getTypes() {
        return types;
    }

    /**
     * Sets the value of the types property.
     * 
     * @param value
     *     allowed object is
     *     {@link Types }
     *     
     */
    public void setTypes(Types value) {
        this.types = value;
    }

    /**
     * Gets the value of the bufferData property.
     * 
     * @return
     *     possible object is
     *     {@link BufferData }
     *     
     */
    public BufferData getBufferData() {
        return bufferData;
    }

    /**
     * Sets the value of the bufferData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BufferData }
     *     
     */
    public void setBufferData(BufferData value) {
        this.bufferData = value;
    }

    /**
     * Gets the value of the stocks property.
     * 
     * @return
     *     possible object is
     *     {@link Stocks }
     *     
     */
    public Stocks getStocks() {
        return stocks;
    }

    /**
     * Sets the value of the stocks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stocks }
     *     
     */
    public void setStocks(Stocks value) {
        this.stocks = value;
    }

}
