//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.24 at 12:41:30 AM BST 
//


package org.pimslims.crystallization.xml.rmxml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.pimslims.crystallization.xml.rmxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.pimslims.crystallization.xml.rmxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ingredient }
     * 
     */
    public Ingredient createIngredient() {
        return new Ingredient();
    }

    /**
     * Create an instance of {@link Types }
     * 
     */
    public Types createTypes() {
        return new Types();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link CasNumbers }
     * 
     */
    public CasNumbers createCasNumbers() {
        return new CasNumbers();
    }

    /**
     * Create an instance of {@link ConditionIngredient }
     * 
     */
    public ConditionIngredient createConditionIngredient() {
        return new ConditionIngredient();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link Stocks }
     * 
     */
    public Stocks createStocks() {
        return new Stocks();
    }

    /**
     * Create an instance of {@link BufferData }
     * 
     */
    public BufferData createBufferData() {
        return new BufferData();
    }

    /**
     * Create an instance of {@link Stock }
     * 
     */
    public Stock createStock() {
        return new Stock();
    }

    /**
     * Create an instance of {@link Aliases }
     * 
     */
    public Aliases createAliases() {
        return new Aliases();
    }

    /**
     * Create an instance of {@link Ingredients }
     * 
     */
    public Ingredients createIngredients() {
        return new Ingredients();
    }

    /**
     * Create an instance of {@link Screen }
     * 
     */
    public Screen createScreen() {
        return new Screen();
    }

    /**
     * Create an instance of {@link TitrationTable }
     * 
     */
    public TitrationTable createTitrationTable() {
        return new TitrationTable();
    }

    /**
     * Create an instance of {@link TitrationPoint }
     * 
     */
    public TitrationPoint createTitrationPoint() {
        return new TitrationPoint();
    }

}
