//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OPPF.XML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.oppf.ox.ac.uk/xsd/RI/Config.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.oppf.ox.ac.uk/xsd/RI/Config.xsd", IsNullable=false)]
    public partial class Config {
        
        private string loggerConfigField;
        
        private string archiveDirField;
        
        private string webDirField;
        
        private string xmlDirField;

        private string doneDirField;

        private string wsPlateEndpointField;

        private string usernameField;

        private string passwordField;

        private string imageBaseUrlField;

        /// <remarks/>
        public string LoggerConfig {
            get {
                return this.loggerConfigField;
            }
            set {
                this.loggerConfigField = value;
            }
        }
        
        /// <remarks/>
        public string ArchiveDir {
            get {
                return this.archiveDirField;
            }
            set {
                this.archiveDirField = value;
            }
        }
        
        /// <remarks/>
        public string WebDir {
            get {
                return this.webDirField;
            }
            set {
                this.webDirField = value;
            }
        }
        
        /// <remarks/>
        public string XmlDir {
            get {
                return this.xmlDirField;
            }
            set {
                this.xmlDirField = value;
            }
        }

        /// <remarks/>
        public string DoneDir
        {
            get
            {
                return this.doneDirField;
            }
            set
            {
                this.doneDirField = value;
            }
        }

        /// <remarks/>
        public string WsPlateEndpoint
        {
            get
            {
                return this.wsPlateEndpointField;
            }
            set
            {
                this.wsPlateEndpointField = value;
            }
        }

        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string ImageBaseUrl
        {
            get
            {
                return this.imageBaseUrlField;
            }
            set
            {
                this.imageBaseUrlField = value;
            }
        }
    }
}
